### ISSUE TITLE
Generate ProducerGranuleId under Data

### ISSUE THREAD

**Issue by hyoklee** [TerraFusion/basicFusion#104]
From input filename 

``
netcdf InputGranules {
}
``

generate the following metadata information.
``
<ProducerGranuleId>    
InputGranules.h5
</ProducerGranuleId>
``

It should be placed after 
``<SizeMBDataGranule/>
``
information.

**Comment by richielo** [comment]
What is netcdf InputGranules { } referring to??

So the producer granule Id is the input file name except the extension is .h5 instead of .cdl right?

**Comment by hyoklee** [comment]
Yes. You can use filename directly from  command line argument instead of parsing the first line of CDL 
``
netcdf filename_without_dot_h5 {
...
}
``

**Comment by richielo** [comment]
Added ProducerGranuleId, handled cases when input is a path instead of a file name

**Comment by hyoklee** [comment]
@richielo When you commit, write a message that refers to this ticket. For example, 'close #104." so that I can easily keep track of changes in your Python code.

**Comment by richielo** [comment]
Okay, will do that for future updates
