### ISSUE TITLE
Perform file validation for 2013 data on ROGER

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#107]
## MOPITT
MOPITT granules are 24 hours. Need to verify that each MOPITT file exists between the first and last days of 2013

## CERES
Same for CERES, except you need to check consistency for both the FM1 and FM2 files. Once you have checked consistency for both file sets individually, I need you to do the following:
1. Step through all FM1 files and find the corresponding FM2 file. If it cannot be found, log it.
1. Do the same, except backwards: stepping through FM2 files and finding corresponding FM1 file.

## MODIS
MODIS granules are 5 minutes. Need to check that every MOD021KM file has corresponding files:

_either_

MOD021KM
MOD03

_or_

MOD021KM
MOD02HKM
MOD02QKM
MOD03

I recommend that you do a four-way check. First step through MOD021KM files, checking for the existence of the MOD02HKM file. If HKM doesn't exist, check MOD03. If MOD03 doesn't exist, log as an error.

Then step through MOD02HKM files. In this case, MOD02HKM should always have a corresponding MOD021KM, MOD02QKM and MOD03 file.

Then step through MOD02QKM files, performing the same checks.

Lastly, step through MOD03 files: Check for a corresponding MOD02HKM file.
if (MOD02HKM exists)
{
    check that MOD02QKM and MOD021KM exist.
    if they don't, log as error
}
else
{
    Check that corresponding MOD021KM file exists. 
    If it doesn't, log as error.
}

This should keep you occupied. If you get done with this, we can finish verification on the rest of the files.

**Comment by richielo** [comment]
Do you have an idea of how many data files may be missing, just to cross check? I just implemented a preliminary script, seems that quite a lot is missing

**Comment by LandonTClipp** [comment]
Sorry for the late reply. There may be a lot of files missing, I will want to see what your script says is missing.
