### ISSUE TITLE
Append platforms information into granule metadata.

### ISSUE THREAD

**Issue by hyoklee** [TerraFusion/basicFusion#108]
For _each_ file name in InputGranules, search NASA CMR and append <platform> information together like below.

`
  <Platforms>
  
    <Platform>
      <ShortName>AM-1</ShortName>
      <Instruments>
        <Instrument>
          <ShortName>MISR</ShortName>
          <Sensors>
            <Sensor>
              <ShortName>DA</ShortName>
            </Sensor>
          </Sensors>
          <OperationModes>
            <OperationMode>Normal</OperationMode>
          </OperationModes>
        </Instrument>
      </Instruments>
    </Platform>
    <Platform>
     <ShortName>TERRA or AM-1 for ASTER?</ShortName>
    </Platform>
  </Platforms>
`

I think there will be inconsistency in metadata. For example, short name for MISR is AM-1 while short name for CERES is TERRA. We need to report this issue to NASA Earthdata as we find inconsistency and ask for advice how to consolidate them properly (i.e., AM-1 or TERRA?).

**Comment by hyoklee** [comment]
The hand-crafted collection metadata [sample_echo10.xml](https://github.com/TerraFusion/basicFusion/blob/master/CMR/sample_echo10.xml) has a very clean Platform information so we may reuse it after NASA's approval. I think this is the way to go if there are too many inconsistencies among all input granule's metadata. Let's search and collect platform information first and ask NASA about their opinion.

**Comment by richielo** [comment]
For our purpose, do we have one single platform? What I have to do is to remove duplicated instruments from what I get from each inputgranule, right?

**Comment by hyoklee** [comment]
You are absolutely right. We are supposed to have a single platform and many instruments in metadata but NASA CMR may return inconsistent results because NASA data producers can make mistake, too.  Let's first collect search result and see how they differ. NASA will appreciate our effort as we find more inconsistencies among metadata. 

I'll add more files into InputGranules attribute soon.

**Comment by richielo** [comment]
Just want to confirm, is this the correct result for MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_AA_F03_0024.hdf? It doesn't look like so. But that's the result I have from the api call tho.."https://cmr.earthdata.nasa.gov/search/granules?readable_granule_name=filename"

> <Granule xmlns:html="http://www.w3.org/1999/xhtml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="">
        <GranuleUR>SS_00107_STD_F0373-GEOTIFF</GranuleUR>
        <InsertTime>2013-08-27T10:39:22Z</InsertTime>
        <LastUpdate>2013-08-27T10:39:22Z</LastUpdate>
        <Collection>
            <DataSetId>SEASAT_SAR_LEVEL1_GEOTIFF</DataSetId>
        </Collection>
    <DataGranule>
        <SizeMBDataGranule>262.27</SizeMBDataGranule>
        <ProducerGranuleId>SS_00107_STD_F0373</ProducerGranuleId>
      <DayNightFlag>UNSPECIFIED</DayNightFlag>
      <ProductionDateTime>2013-08-27T10:39:22Z</ProductionDateTime>
    </DataGranule>
        <Temporal>
            <RangeDateTime>
                <BeginningDateTime>1978-07-04T12:06:00Z</BeginningDateTime>
                <EndingDateTime>1978-07-04T12:06:15Z</EndingDateTime>
            </RangeDateTime>
        </Temporal>
        <Spatial>
            <HorizontalSpatialDomain>
                <Geometry>
                    <GPolygon>
                        <Boundary>
              <Point>
                <PointLongitude>-111.6512</PointLongitude>
                <PointLatitude>19.238</PointLatitude>
              </Point>
              <Point>
                <PointLongitude>-110.6602</PointLongitude>
                <PointLatitude>19.6319</PointLatitude>
              </Point>
              <Point>
                <PointLongitude>-110.3003</PointLongitude>
                <PointLatitude>18.7734</PointLatitude>
              </Point>
              <Point>
                <PointLongitude>-111.2851</PointLongitude>
                <PointLatitude>18.3807</PointLatitude>
              </Point>
                        </Boundary>
                    </GPolygon>
                </Geometry>
            </HorizontalSpatialDomain>
        </Spatial>
    <OrbitCalculatedSpatialDomains>
      <OrbitCalculatedSpatialDomain>
        <OrbitNumber>107</OrbitNumber>
      </OrbitCalculatedSpatialDomain>
    </OrbitCalculatedSpatialDomains>
        <Platforms>
            <Platform>
                <ShortName>SEASAT 1</ShortName>
                <Instruments>
                    <Instrument>
                        <ShortName>SAR</ShortName>
                        <Sensors>
                            <Sensor>
                                <ShortName>STD</ShortName>
                            </Sensor>
                        </Sensors>
                    </Instrument>
                </Instruments>
            </Platform>
        </Platforms>
        <AdditionalAttributes>
            <AdditionalAttribute>
                <Name>FLIGHT_LINE</Name>
                <Values>
                    <Value>NULL</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>OFF_NADIR_ANGLE</Name>
                <Values>
                    <Value>-1</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>MD5SUM</Name>
                <Values>
                    <Value>9bdccd162a8726c7baf6998b4292ca87</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>GRANULE_TYPE</Name>
                <Values>
                    <Value>SEASAT_STD_FRAME</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>ASCENDING_DESCENDING</Name>
                <Values>
                    <Value>ASCENDING</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>FAR_END_LAT</Name>
                <Values>
                    <Value>19.6319</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>INSAR_STACK_SIZE</Name>
                <Values>
                    <Value>0</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>BEAM_MODE_TYPE</Name>
                <Values>
                    <Value>STD</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>INSAR_BASELINE</Name>
                <Values>
                    <Value>0</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>CENTER_FRAME_ID</Name>
                <Values>
                    <Value>380</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>CENTER_ESA_FRAME</Name>
                <Values>
                    <Value>380</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>ACQUISITION_DATE</Name>
                <Values>
                    <Value>1978-07-04T12:06:15Z</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>MISSION_NAME</Name>
                <Values>
                    <Value>NULL</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>CENTER_LON</Name>
                <Values>
                    <Value>-110.9745</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>NEAR_START_LAT</Name>
                <Values>
                    <Value>18.3807</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>BEAM_MODE</Name>
                <Values>
                    <Value>Standard</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>BEAM_MODE_DESC</Name>
                <Values>
                    <Value>ERS-1,ERS-2,JERS-1,SEASAT,SMAP Standard Beam SAR</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>PROCESSING_TYPE</Name>
                <Values>
                    <Value>GEOTIFF</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>PROCESSING_DESCRIPTION</Name>
                <Values>
                    <Value>L-Band backscatter GeoTIFF</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>FRAME_NUMBER</Name>
                <Values>
                    <Value>0373</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>PROCESSING_LEVEL</Name>
                <Values>
                    <Value>L1</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>PROCESSING_DATE</Name>
                <Values>
                    <Value>2013-08-27 10:39:22.261711</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>NEAR_START_LON</Name>
                <Values>
                    <Value>-111.2851</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>DOPPLER</Name>
                <Values>
                    <Value>-1</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>FAR_START_LAT</Name>
                <Values>
                    <Value>18.7734</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>NEAR_END_LON</Name>
                <Values>
                    <Value>-111.6512</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>PROCESSING_TYPE_DISPLAY</Name>
                <Values>
                    <Value>Level One GeoTIFF product</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>POLARIZATION</Name>
                <Values>
                    <Value>HH</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>FAR_START_LON</Name>
                <Values>
                    <Value>-110.3003</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>THUMBNAIL_URL</Name>
                <Values>
                    <Value>https://datapool.asf.alaska.edu/THUMBNAIL/SS/SS_00107_STD_F0373_THUMBNAIL.jpg</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>ASF_PLATFORM</Name>
                <Values>
                    <Value>SEASAT</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>INSAR_STACK_ID</Name>
                <Values>
                    <Value>0</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>LOOK_DIRECTION</Name>
                <Values>
                    <Value>R</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>PATH_NUMBER</Name>
                <Values>
                    <Value>106</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>NEAR_END_LAT</Name>
                <Values>
                    <Value>19.238</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>FARADAY_ROTATION</Name>
                <Values>
                    <Value>NA</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>FAR_END_LON</Name>
                <Values>
                    <Value>-110.6602</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>BYTES</Name>
                <Values>
                    <Value>275014889</Value>
                </Values>
            </AdditionalAttribute>
            <AdditionalAttribute>
                <Name>CENTER_LAT</Name>
                <Values>
                    <Value>19.0068</Value>
                </Values>
            </AdditionalAttribute>
        </AdditionalAttributes>
    <OnlineAccessURLs>
        <OnlineAccessURL>
          <URL>https://datapool.asf.alaska.edu/GEOTIFF/SS/SS_00107_STD_F0373_tif.zip</URL>
        </OnlineAccessURL>
    </OnlineAccessURLs>
        <Orderable>true</Orderable>
        <Visible>true</Visible>
  <AssociatedBrowseImageUrls>
      <ProviderBrowseUrl>
      <URL>https://datapool.asf.alaska.edu/BROWSE/SS/SS_00107_STD_F0373_BROWSE.jpg</URL>
      </ProviderBrowseUrl>
  </AssociatedBrowseImageUrls>
</Granule>

**Comment by hyoklee** [comment]
The result doesn't look right. I think you forgot to include \[\] in your URL. 
```
readable_granule_name\[\]=
```

**Comment by richielo** [comment]
Do you mean I need this \[\]?

**Comment by richielo** [comment]
Yes I just tried that, it's still not getting the right thing, something is wrong with my api call

**Comment by hyoklee** [comment]
Can you print out the URL and try the same URL with curl from command line?

**Comment by richielo** [comment]
Okay, I am using this now which is working for the MISR file. But the hit for the AST file is 0, is that a valid file? 
https://cmr.earthdata.nasa.gov/search/granules?pretty=True&echo_compatible=True&readable_granule_name=

**Comment by hyoklee** [comment]
I also got 0 for ASTER.  Please ask support@earthdata.nasa.gov<mailto:support@earthdata.nasa.gov> why ASTER product is not searchable by name.

**Comment by richielo** [comment]
Thanks Joe, if you have the time, it would be great if you can cross check with me just to be sure

For the 7 files in InputGranules, 1 aster file cannot be found and only 3 among the 7 have the attribute Platforms.

Also, as you predicted, among the three, 2 are called AM-1, the other is called TERRA

**Comment by hyoklee** [comment]
Great finding. Can you put the 6 ECHO10 XML granule files into GitHub so that we can refer them easily when we write a report to NASA?

**Comment by richielo** [comment]
They are up here now, there's a duplicated file name in the cdl, so I removed that too. Now, only 2 files have platforms which are named differently

Do you want me to consider them as the same platform or generate them separately?

**Comment by hyoklee** [comment]
Let's ask NASA first since there could be a reason for calling the same platform differently. Would you please ask support@earthdata.nasa.gov again whether it is OK to safely consolidate them into "TERRA"?

Before submitting the issue, can you use "tidy -imu filename.xml" to reformat the downloaded xml files with proper indentation so that we can view the files more easily on GitHub?

**Comment by richielo** [comment]
Dr. Girolamo mentioned that AM-1 is the pre-launch name and TERRA is the official name now, so I guess it's fine for us to do use TERRA?

**Comment by hyoklee** [comment]
I see. Yes, let's use TERRA and please move on to  #115.

**Comment by richielo** [comment]
Okay, I will do so once I am done with this, thanks

**Comment by richielo** [comment]
For different files, say if they have the same instrument MISR, are the sensors tags inside supposed to be the same? So once I included one MISR from one file I can discard others with same instrument name. Or this is not necessarily true?

**Comment by richielo** [comment]
@hyoklee , Just need your confirmation about the issue I mentioned above to finish this up. The generated file can be found in InputGranules_generated.xml as an example

**Comment by hyoklee** [comment]
@richielo Your fix looks good. I'll close the ticket.
