### ISSUE TITLE
Adding dimensions for PointingAngle and SolarGemetry. 

### ISSUE THREAD

**Issue by kyang2014** [TerraFusion/basicFusion#114]
Currently  the ncdump output
group: PointingAngle {
      dimensions:
        phony_dim_56 = 1 ;
      variables:
        float SWIR(phony_dim_56) ;
        float TIR(phony_dim_56) ;
      } // group PointingAngle
 group: Solar_Geometry {
      dimensions:
        phony_dim_57 = 1 ;
      variables:
        float SolarAzimuth(phony_dim_57) ;
        float SolarElevation(phony_dim_57) ;
      } // group Solar_Geometry

That means we didn't add dimensions for these variables.

I. We should use PointingAngle_g1(g1 is for granule) for variable SWIR and TIR dimension names. The output should be 
group: PointingAngle {
      dimensions:
        PointingAngle__g1 = 1 ;
      variables:
        float SWIR( PointingAngle__g1) ;
        float TIR( PointingAngle__g1) ;
      } // group PointingAngle

II. We should also use Solar_Geometry_g1(g1 is granule appendix) for the dimension names of SolarAzimuth and SolarElevation. 

The output should be like:

 group: Solar_Geometry {
      dimensions:
       Solar_Geometry_g1 = 1 ;
      variables:
        float SolarAzimuth(Solar_Geometry_g1) ;
        float SolarElevation(Solar_Geometry_g1) ;
      } // group Solar_Geometry

**Comment by LandonTClipp** [comment]
Will these dimensions be pure dimensions?

**Comment by kyang2014** [comment]
Yes, that’s correct.

**Comment by LandonTClipp** [comment]
Issue complete. 

Quick question: does HDF5 guarantee that uninitialized datasets are set to 0?
