### ISSUE TITLE
Test CMR ingestion.

### ISSUE THREAD

**Issue by hyoklee** [TerraFusion/basicFusion#115]
Test our current collection / granule XML files with UAT (User Acceptance Testing) CMR server using "FUSION" provider name. Use PyCMR to ingest, search, and delete our metadata.  Ingestion failure is OK. Just try and see what CMR returns.

**Comment by richielo** [comment]
Is it a must to use pyCMR? It's still not working on my side, I am calling the API call directly,  maybe I should drop by to see how can we solve that?

**Comment by hyoklee** [comment]
Testing with curl is fine at this point. Please create a separate Python script for ingestion testing and put it under CMR/.

**Comment by hyoklee** [comment]
@richielo, you're working on this issue, right?

**Comment by LandonTClipp** [comment]
Hi Mr. Lee. We had to steal Richie away from you to work on the basic fusion database. This is to meet a deadline for the quarterly report (process a year of basic fusion data). You should have been CC'ed in one of my emails about that. We've asked him to give the database his full attention for now.

**Comment by hyoklee** [comment]
@LandonTClipp, now I understand your email. @richielo, work on this issue when the urgent issue for basic fusion database is resolved.

**Comment by richielo** [comment]
Do I have my own account to test it now?? Where can I verify that I have one? Thanks Joe

**Comment by hyoklee** [comment]
Yes, you do. I think you signed up the other day with uat.urs.earthdata.nasa.gov.

**Comment by richielo** [comment]
@hyoklee , I have coded up a simple interface to do so. The communication with the api has been successful, you can find it in cmr_ingest.py

**Comment by hyoklee** [comment]
@richielo Your code looks very good so far. Keep testing this script with our sample collection metadata first (#119) until it passes NASA UAT CMR server. Then, test granule sample (#120) until it passes.
