### ISSUE TITLE
MOPITT 2013 missing Data

### ISSUE THREAD

**Issue by shashankbansal6** [TerraFusion/basicFusion#117]
The following files are missing from the MOPITT data for the year 2013. This is for the MOP01.005 directory in /projects/TDataFus/gyzhao/TF/data/MOPITT/
MOP01.005/2013.03.25 
MOP01.005/2013.03.26 
MOP01.005/2013.03.27 
MOP01.005/2013.03.28 
MOP01.005/2013.03.31 
MOP01.005/2013.03.30 
MOP01.005/2013.04.02
MOP01.005/2013.04.03
MOP01.005/2013.04.01
MOP01.005/2013.04.05
MOP01.005/2013.04.04
MOP01.005/2013.03.29

**Comment by sandman0o0** [comment]
Are we actually using the 005 dataset?  I thought after talking with Guangyu a while back we were only using the 007 data.

**Comment by shashankbansal6** [comment]
The 007 in ROGERS is missing more data. Its missing all of the dates above and the data for 2013.04.06.

**Comment by LandonTClipp** [comment]
I have forgotten that we agreed on the 007 data, so in that case yes, just worry about 007 dataset.
