### ISSUE TITLE
Investigate collection validation failure.

### ISSUE THREAD

**Issue by hyoklee** [TerraFusion/basicFusion#119]
I tried ingestion of sample_echo10.xml and NASA server returned the following error:

```
<?xml version="1.0" encoding="UTF-8"?><errors><error>Line 1 - cvc-complex-type.\
2.4.a: Invalid content was found starting with element 'RevisionDate'. One of '\
{DOI, CollectionDataType, Orderable}' is expected.</error></errors>
```

We need to investigate what more elements should  be provided to pass ingestion.

**Comment by richielo** [comment]
We would need something like this: `<Orderable>false</Orderable>`

Orderable Granules – This ACL dynamically applies to all granules within a static listing of collections that contain orderable granules. Order permissions to this ACL may be granted to the Registered Users and Guest Users system level groups to allow for order creation and submission

I am not sure what this means though

**Comment by hyoklee** [comment]
Yes,  Orderable=false sounds good. Can you add it into our sample_echo10.xml?

**Comment by richielo** [comment]
I updated the file. Now there are no errors but only warnings, which I don't even see those tags in the sample they provided, so it should be fine for now.

<?xml version="1.0" encoding="UTF-8"?><result><warnings>After translating item to UMM-C the metadata had the following issue: object has missing required properties (["CollectionProgress","SpatialExtent"])</warnings></result>

**Comment by hyoklee** [comment]
Great! I'm not familiar with the message '''After translating item to UMM-C the metadata had the following issue: object has missing required properties (["CollectionProgress","SpatialExtent"])''' Can you investigate it further on your own by searching for CMR document & asking questions to NASA _after making granule ingestion pass_?

**Comment by richielo** [comment]
SpatialExtent actually corresponds to the Spatial tag in echo10, so I added random spatial information copied from the sample, now the warning is gone.

For CollectionProgress, apparently the sample file given by CMR also has the same warning when I tried to validate it. Therefore, I think we are safe to ignore that warning

**Comment by hyoklee** [comment]
I got the following response with our sample collection metadata. 

`<?xml version="1.0" encoding="UTF-8"?><result><concept-id>C1219815667-FUSION</concept-id><revision-id>1</revision-id><warnings>After translating item to UMM-C the metadata had the following issue: object has missing required properties (["CollectionProgress","SpatialExtent"])</warnings></result>`

So, our collection metadata passed ingestion.  Great job, @richielo!
