### ISSUE TITLE
Investigate Granule ingestion error.

### ISSUE THREAD

**Issue by hyoklee** [TerraFusion/basicFusion#120]
InputGranules.xml requires GranuleUR. 

```
<?xml version="1.0" encoding="UTF-8"?><errors><error>Line 1 - cvc-complex-type.\
2.4.a: Invalid content was found starting with element 'InputGranules'. One of \
'{GranuleUR}' is expected.</error></errors>
```

We need to investigate how to generate unique record number for each granule.  One possibility is to combine all GranuleUR of input granules.

**Comment by richielo** [comment]
I tried concatenating all the individual URs into one, it works. It passes that test case. But now InsertTime is expected

**Comment by richielo** [comment]
@hyoklee , for granules, it's missing a DayNightFlag, but the InputGranules have different day night flags, what should we do about that?

**Comment by hyoklee** [comment]
@richielo  How about   `<DayNightFlag>UNSPECIFIED</DayNightFlag>` as used in MISR?

**Comment by richielo** [comment]
That works. Last update time and Insert time are required, so I use the current timestamp of when the script is ran, so they are the same, is that okay?

For granules, it also needs something like this:
`  <Collection>
    <DataSetId>CER_SSF_Terra-FM1-MODIS_Edition4A</DataSetId>
  </Collection>`
How should we deal with multiple names for all the granules? would this work?
`<Collections>
<Collection>
    <DataSetId>CER_SSF_Terra-FM1-MODIS_Edition4A</DataSetId>
  </Collection>
<Collection>
    <DataSetId>MISR_XXXXX</DataSetId>
  </Collection>
</Collections>`

**Comment by richielo** [comment]
Just tried, the latter won't work, the only thing we can do is: 
`<Collection> <DataSetId>name1</DataSetId>  
<DataSetId>name2</DataSetId>  
<DataSetId>name3</DataSetId>  
<DataSetId>name4</DataSetId> </Collection>`
Is this weird?

Also, once that's passed we would need one of these - {TwoDCoordinateSystem, Price, OnlineAccessURLs, OnlineResources, Orderable}, do we have anything like these in our files? or I can just put orderable flag?

Thanks

**Comment by hyoklee** [comment]
There should be only one like: `<DataSetId>Terra Fusion Level 2 Data</DatasetId>`. The exact value should be determined and reviewed by the team. The important thing is that it should be exactly same and shared between collection and granule metadata.

**Comment by richielo** [comment]
Okay, I guess we have to wait for the decision from the team.
Other than that, what's left is the second issue, do we just include all the  OnlineAccessURLs, OnlineResources, Orderable from all the files?

**Comment by hyoklee** [comment]
@richielo That will be nice. Let's include them from all files.

**Comment by richielo** [comment]
What about tags that are specific to some instruments? Like Ceres has MeasuredParameters, MISR has TwoDCoordinateSystem and MOPIT has lot of AdditionalAttribute

**Comment by hyoklee** [comment]
@richielo Let's try to merge MeasuredParameters, TwoDCoordinateSystem, but not AdditionalAttribute.  Then, please test ingestion if it passes.

**Comment by richielo** [comment]
By merge you mean grabbing them from corresponding MISR and CERES files right?

**Comment by hyoklee** [comment]
Right. However, don't spend too much time on merging yet. Just grab MeasuredParameters from input MISR porduct only. Then, let's make ingestion work first. If it is successful,  let's merge more MeasuresParameters from input files (listed under InputGranules).

**Comment by richielo** [comment]
I don't quite understand. Do you mean the InputGranules inside the MISR file will have to be considered too?

**Comment by hyoklee** [comment]
No. We need to merge MeasuredParameters from CMR results of the products listed only in our TerraFusion CDL (e.g., InputGranules.cdl)  as you did with Platforms. 
`
:InputGranules = "MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_AA_F03_0024.hdf,AST_L1T_00307032007162020_20150520034221_121033.hdf,AST_L1T_00307032007164651 
`

**Comment by richielo** [comment]
@hyoklee I have uploaded the newly generated granule xml file, I manually added Collection name and ID for testing purpose. I am having an issue that, it's giving me this '{TwoDCoordinateSystem, Price, OnlineAccessURLs, OnlineResources, Orderable}' is expected, even though they already exist. I tried adding price but they don't make a difference.

**Comment by hyoklee** [comment]
@richielo Now I got the following error during validation after collection metadata ingestion. 

`<?xml version="1.0" encoding="UTF-8"?><errors><error><path>PlatformRefs/0/InstrumentRefs</path><errors><error>The following list of Instrument short names did not exist in the referenced parent collection: [CERES-FM1].</error></errors></error><error><path>PlatformRefs/0/InstrumentRefs/0/SensorRefs</path><errors><error>The following list of Sensor short names did not exist in the referenced parent collection: [AA].</error></errors></error><error><path>PlatformRefs/0/InstrumentRefs/0</path><errors><error>The following list of Instrument operation modes did not exist in the referenced parent collection: [Normal].</error></errors></error><error><path>PlatformRefs/0/InstrumentRefs/1/SensorRefs</path><errors><error>The following list of Sensor short names did not exist in the referenced parent collection: [CERES-FM1].</error></errors></error><error><path>TwoDCoordinateSystem</path><errors><error>The following list of Tiling Identification System Names did not exist in the referenced parent collection: [MISR].</error></errors></error><error><path>SpatialCoverage/Orbit</path><errors><error>[Orbit] cannot be set when the parent collection's GranuleSpatialRepresentation is NO_SPATIAL</error></errors></error></errors>`

It seems that we need to adjust GranuleSpatialRepresentation in collection metadata.

**Comment by richielo** [comment]
Should the generation of granules metadata depend on the collection metadata or should it be the other way round? 

Those seem tough to fix

**Comment by hyoklee** [comment]
Let's try copying Instruments xml content from granule metadata into collection metadata. This means collection metadata depends on granule metadata.

**Comment by richielo** [comment]
I think copying may not work? I tried moving components from InputGranules_generated.xml to sample_echo10.xml, and it's giving all sorts of errors for collection validation

**Comment by hyoklee** [comment]
Would you please post error messages? I'm also testing copying Instruments xml content from collection to granule now. We need to figure out how to make this work.

**Comment by richielo** [comment]
I have something like this

<?xml version="1.0" encoding="UTF-8"?><errors><error>Line 136 - cvc-complex-type.2.4.a: Invalid content was found starting with element 'TwoDCoordinateSystem'. One of '{AdditionalAttributes, CSDTDescriptions, CollectionAssociations, Campaigns, AlgorithmPackages, TwoDCoordinateSystems, SpatialInfo, OnlineAccessURLs, OnlineResources, AssociatedDIFs, Spatial, MetadataStandardName, MetadataStandardVersion, ProductFlag, AssociatedBrowseImages, AssociatedBrowseImageUrls}' is expected.</error><error>Line 178 - cvc-complex-type.2.4.a: Invalid content was found starting with element 'Orbit'. One of '{ZoneIdentifier, Geometry}' is expected.</error><error>Line 186 - cvc-complex-type.2.4.b: The content of element 'Spatial' is not complete. One of '{VerticalSpatialDomain, OrbitParameters, GranuleSpatialRepresentation}' is expected.</error></errors>

**Comment by hyoklee** [comment]
@richielo The above error occurs when the order of element is wrong.  Did you review my commit  d2efa44?

**Comment by richielo** [comment]
I have updated the sample_echo10.xml, incorporating the granules information. This has passed the validation. Please try again and see if you still see the granule ingestion errors. I can't do it since I am having permission issues. Thanks!

**Comment by hyoklee** [comment]
@richielo I am quite busy now so please contact NASA Earthdata support to resolve permission issue and test granule ingestion.

**Comment by richielo** [comment]
Good news, the ingestion script can now handle collection update.
Also, granule validation has been successful with the generated xml files, using the ingestion script. 

The only thing left is granule ingestion, which is giving me status code 500 - An Internal Error has occurred. According to the documentation, that may be something wrong on CMR's side, in contact with the team to see what's going on

**Comment by hyoklee** [comment]
@richielo Great job, Richie! Please make granule ingestion work by working closely with NASA CMR team and we will reach another milestone.

**Comment by richielo** [comment]
I am still waiting for their response. There's not much I can do at this moment..

**Comment by hyoklee** [comment]
I used curl and I could ingest successfully. 

`
[nene:~/basicFusion/CMR] hyoklee% curl -i -XPUT -H "Content-type: application/echo10+xml" -H "Echo-Token:XXXX" https://cmr.uat.earthdata.nasa.gov/ingest/providers/FUSION/granules/terra_fusion_1 -d @InputGranules_generated.xml
HTTP/1.1 100 Continue

HTTP/1.1 201 Created
CMR-Request-Id: 94be7fc7-3f88-46e1-b12e-8bc33ec45800
Content-Type: application/xml; charset=ISO-8859-1
Date: Tue, 13 Jun 2017 13:25:50 GMT
Server: nginx
Strict-Transport-Security: max-age=31536000; includeSubDomains;
Content-Length: 126
Connection: keep-alive

<?xml version="1.0" encoding="UTF-8"?><result><concept-id>G1220125693-FUSION</concept-id><revision-id>1</revision-id></result>
`

**Comment by hyoklee** [comment]
![screen shot 2017-06-13 at 8 32 40 am](https://user-images.githubusercontent.com/4994401/27084844-f50fd62e-5012-11e7-9df2-ec0f982e7fe6.png)

**Comment by richielo** [comment]
Okay, Thanks a lot for the information. I did not submit any nativeID, I would need to update my code. Thanks again joe
