### ISSUE TITLE
MODIS missing 2013 files

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#123]
The attached text file list the missing MODIS 2013 files. Here is how to parse the file:

The errq file iterates through all of the MODIS QKM files that were found and checks that a corresponding 1KM, HKM and MOD03 file exist (corresponding based on the date listed in the file name). If the script doesn't find a file that is supposed to exist, it lists the name of the file that should exist but doesn't. For instance:
```

Q: 054 MOD02HKM.A2013054.2200
Q: 054 MOD02HKM.A2013054.2320
Q: 054 MOD02HKM.A2013054.2035
Q: 054 MOD02HKM.A2013054.1515
...
```

This is telling us that by iterating through the QKM files, we were expecting to find the listed MOD02HKM files but did not find them. The three digit number in the middle denotes which directory in the 2013 MODIS directory this file should have existed.

[errq.txt](https://github.com/TerraFusion/basicFusion/files/1048645/errq.txt)

**Comment by richielo** [comment]
Here's the list of MODIS files that are either non-existent or empty.


[missing_list.txt](https://github.com/TerraFusion/basicFusion/files/1048822/missing_list.txt)

**Comment by LandonTClipp** [comment]
Please see the attached missing file list.


[modis_missing_list.txt](https://github.com/TerraFusion/basicFusion/files/1062210/modis_missing_list.txt)

**Comment by sandman0o0** [comment]
These missing MOD02HKM files have been pulled down to ROGER.

**Comment by LandonTClipp** [comment]
Thanks, it appears to be fixed. I will have @richielo run another round of MODIS checks.
