### ISSUE TITLE
BF Structure changes

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#132]
I just checked the structure of the one orbit basic fusion file.  It is much better. Still a few areas need to be fixed.
1. ASTER Dimensions: we don’t need to have PointingAngle_g1, PointingAngle_g2…. And Solar_Geometry_g1……We just need one dimension for PointingAngle and one dimension for Solar_Geometry. To distinguish the ASTER from other sensors, Let make the dimension name for all PointingAngle variables: ASTER_PointingAngleDim and Solar_Geometry to ASTER_Solar_GeometryDim.
 
1. MODIS coordinates:
There are some MODIS variables that are 3-D arrays.
For example,
float EV_1KM_Emissive(Band_1KM_Emissive_MODIS_SWATH_Type_L1B, _10_nscans_MODIS_SWATH_Type_L1B, Max_EV_frames_MODIS_SWATH_Type_L1B)
For group granule1, coordinates need to be “/MODIS/granule1/_1KM/Geolocation/Longitude /MODIS/granule1/_1KM/Geolocation/Latitude Band_1KM_Emissive_MODIS_SWATH_Type_L1B”
The variable Band_1KM_Emissive_MODIS_SWATH_Type_L1B also needs to be in.
Also the name of the attribute should be “coordinates” rather than “Coordinates”.

**Comment by LandonTClipp** [comment]
@kyang2014 
You say "For group granule1, ". Do you mean that _only_ MODIS granule1 should have the "Band_1KM_Emissive_MODIS_SWATH_Type_L1B" appended to coordinates?

**Comment by kyang2014** [comment]
No, This should apply for all MODIS granules.
Specially for all MODIS granules,
If we see that an HDF5 dataset is a 3-D array and one of the dimension has a corresponding  band number variable like Band_1KM_Emissive_MODIS_SWATH_Type_L1B,
We should add that variable name  in the coordinates attribute value.

**Comment by LandonTClipp** [comment]
Got it, thanks.

**Comment by LandonTClipp** [comment]
Issue fixed. Pending new BF file for you to review.

**Comment by kyang2014** [comment]
Where is the new file?

**Comment by LandonTClipp** [comment]
Sorry should have specified, new files are being generated now. Will take a little bit.

**Comment by kyang2014** [comment]
It is all right. Just let me know when it is done.

**Comment by LandonTClipp** [comment]
The files are ready at:

```/projects/TDataFus/fusionTesting/output/Jun9.1```

The corresponding input files are in `../input/Jun9.1`.
