### ISSUE TITLE
Document and clean up CMR code.

### ISSUE THREAD

**Issue by hyoklee** [TerraFusion/basicFusion#138]
The two python codes cdl2echo10.py and cmr_ingest.py need a detailed documentation. Also, please remove unused code. Reformat codes using pep8. Follow https://google.github.io/styleguide/pyguide.html as well.

**Comment by richielo** [comment]
Okay. I am on break right now. I will try to finish it as soon as I can

**Comment by richielo** [comment]
Removed unused codes and added descriptions to functions as advised

**Comment by hyoklee** [comment]
@richielo Welcome back!

**Comment by richielo** [comment]
Thanks! I am new to documentation stuffs so probably they are not perfect. Just let me know for any next steps we may need to take
