### ISSUE TITLE
character in the _FillValue

### ISSUE THREAD

**Issue by kyang2014** [TerraFusion/basicFusion#140]
In the CDL you sent, I noticed that there's a line that says "TrackCount = 438U". Do you know what U means in this attribute? I hope that U is not accidentally appended due to processing error.

**Comment by LandonTClipp** [comment]
CDL is from the ncdump utility

**Comment by LandonTClipp** [comment]
I researched the U in track count. TrackCount is written as an unsigned 16 bit integer, there is no way that a character could be appended to the attribute. It must be an identifier that ncdump adds.

**Comment by kyang2014** [comment]
The issue is a bug in the MOPITT handling. Fixed.
