### ISSUE TITLE
CERES missing files

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#145]
The following CERES file is missing from 2013:
```
/projects/TDataFus/gyzhao/TF/data/CERES/FM2/SSF/2013/CER_SSF_Terra-FM2-MODIS_Edition4A_400403.2013012812
```

**Comment by LandonTClipp** [comment]
@sandman0o0 I'll leave this to you.

**Comment by sandman0o0** [comment]
Working on getting this. Looks like the data isn't on the FTP site currently, so I've asked the NASA folks and copied Guangyu to hopefully have those be made available again.

**Comment by sandman0o0** [comment]
Turns out that this specific file was never produced.  I have tracked down missing files from other years though and will be working to get those pulled.

**Comment by sandman0o0** [comment]
I have everything that exists at the source, was missing on our end, and/or did not match the NASA md5sums.  Everything here should now be complete.

**Comment by LandonTClipp** [comment]
Okay thank you.
