### ISSUE TITLE
CERES.c is not adding FM1 file

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#146]
The following bug was discovered during the 2013 processing on ROGER.

The BF program fails with the following input:

```
/projects/TDataFus/fusionTesting/input/2013/input74649.txt
```

I have used GDB to find the error. Here are the following CERES files in this input.txt file:

```
/projects/TDataFus/gyzhao/TF/data/CERES/FM1/SSF/2013/CER_SSF_Terra-FM1-MODIS_Edition4A_400403.2013123010
/projects/TDataFus/gyzhao/TF/data/CERES/FM2/SSF/2013/CER_SSF_Terra-FM2-MODIS_Edition4A_400403.2013123010
/projects/TDataFus/gyzhao/TF/data/CERES/FM1/SSF/2013/CER_SSF_Terra-FM1-MODIS_Edition4A_400403.2013123011
/projects/TDataFus/gyzhao/TF/data/CERES/FM2/SSF/2013/CER_SSF_Terra-FM2-MODIS_Edition4A_400403.2013123011
/projects/TDataFus/gyzhao/TF/data/CERES/FM1/SSF/2013/CER_SSF_Terra-FM1-MODIS_Edition4A_400403.2013123012
/projects/TDataFus/gyzhao/TF/data/CERES/FM2/SSF/2013/CER_SSF_Terra-FM2-MODIS_Edition4A_400403.2013123012
```

The basic fusion follows this flow:

1. It parses the first two CERES files (FM1 and FM2 for 2013123010) and finds that these files are out of bounds of the orbit. It skips these files.
1. It parses the `CER_SSF_Terra-FM1-MODIS_Edition4A_400403.2013123011` file and finds it to be out of bounds. It skips it.
1. It parses the above file's corresponding FM2 file `CER_SSF_Terra-FM2-MODIS_Edition4A_400403.2013123011` and does not find it to be out of bounds. It attempts to process this file.
1. In attempting to process this FM2 file, the CERES function expected to find the CERES group in the HDF file, but because no CERES granule had been processed yet, it does not find this group. A failure occurs.

@kyang2014 Any ideas why your subsetting function would give two different results for corresponding FM1/FM2 subsetting indexes?

**Comment by kyang2014** [comment]
Landon,


Thanks for discovering this. Could you have a first round of checking to see if these six files, especially the /projects/TDataFus/gyzhao/TF/data/CERES/FM1/SSF/2013/CER_SSF_Terra-FM1-MODIS_Edition4A_400403.2013123011

/projects/TDataFus/gyzhao/TF/data/CERES/FM2/SSF/2013/CER_SSF_Terra-FM2-MODIS_Edition4A_400403.2013123011

if they have the same file structure and the array index for the radiance/time variables?

**Comment by LandonTClipp** [comment]
I have checked these files, they all have the same structure. The FM1 and FM2 files do not have the same number of elements for their "Time of Observation" and the other corresponding radiance datasets. I do not know if that is something that needs to be considered. Here is some information that may be helpful:
```
2013123011 FM2 start: 2456656.958333376
2013123011 FM2 end:  2456656.999999884
```

```
2013123011 FM1 start: 2456656.958340478
2013123011 FM1 end:  2456656.999992643
```

Orbit 74649:

```
74649 203 2013-12-30T10:47:48Z 2013-12-30T12:26:41Z
```

**Comment by kyang2014** [comment]
Thanks, That’s exactly what I want to know. It makes sense that there are some data in FM2 but not in FM1 since FM1 ends earlier.

**Comment by LandonTClipp** [comment]
@kyang2014 

Let me know if you have time to work on this next week. If not, I can fix this.

**Comment by kyang2014** [comment]
It will be great that you can tackle it next week first. I will take a look at the code and all the issues in early July.

**Comment by LandonTClipp** [comment]
Another problem. I looked at the output granule one orbit before this one, it is not adding the 2013123010 file, so that file is being completely skipped in all granules. Also the 2013123011 FM1 file is being completely skipped.

**Comment by kyang2014** [comment]
Up to this point, I would like you to detailed  document the issues you find related to CERES rather than fixing anything not obvious. I will check the code and if it is a bug inside the code, I will fix them.  I suspect the time is not right in the CERES file. Anyway, finding the problem can greatly help me.

**Comment by LandonTClipp** [comment]
Potential problem (Dr. Yang, please view this comment on GitHub for proper formatting):

In the binarySearchUTC function, there is this code:

```
   if ( cmp_orbit_mark_time >=0 && cmp_orbit_adj_time <0)
        return middle;
    else if(cmp_orbit_mark_time <0)
        return binarySearchUTC(jd,target,0,middle);
    else
        return binarySearchUTC(jd,target,middle,end_index);
```

As is obvious, this function is using a recursive implementation of the binary search. Unless I am terribly mistaken, this code will produce incorrect results. The recursive calls have incorrect boundaries. The code should look something like this:

```
if ( middle < target )
    return binarySearchUTC(jd, target, leftBound, middle )
else if ( middle > target )
    return binarySearchUTC(jd, target, middle, rightBound)
else
    return middle
```

Notice that I give the variables "leftBound" and "rightBound" instead of "0" and "end_index". The boundaries in a recursive binary search function call will often __not__ simply be the limits of the array. Take for example the array:

| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 

Let our target be 4. The algorithm will look as such:

| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 
  &nbsp;&nbsp;L&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;R

| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 
&nbsp;&nbsp;L&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;R

| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | &nbsp;&nbsp;&nbsp;&nbsp;<<<  Notice position of L. This is the key difference!!! 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;L&nbsp;&nbsp;&nbsp;^&nbsp;&nbsp;&nbsp;R                  

I recommend you use my binarySearch function if possible.

**Comment by kyang2014** [comment]
Cannot pin down easily whether this is the case. Have you found any CERES case that proves the recursive approach is wrong?  I still don’t have time to check this in detail. If you find any CERES case that gives back the incorrect result, that will be great.

**Comment by LandonTClipp** [comment]
I did intensive testing if the function, it appears to be working normally. So that is not the issue. I will continue searching.

**Comment by LandonTClipp** [comment]
Orbit 74649:
Start time: 2013-12-30T10:47:48
End time: 2013-12-30T12:26:41Z
 
File:
```/projects/TDataFus/gyzhao/TF/data/CERES/FM1/SSF/2013/CER_SSF_Terra-FM1-MODIS_Edition4A_400403.2013123011```

Start time: 2013-12-30T11:00:00
End time: 2013-12-30T11:59:59Z

It is obvious that subsetting is not being performed correctly. Since @kyang2014 cannot devote time (as per email), I will dive into this problem. This is critical.

Edit: I found where the bug is occuring. For the file listed, the program finds this to be the starting day:
```
(gdb) print granule_start_time.day
$5 = 29 '\035'
```
Similar problem for the granule_end_time.

**Comment by LandonTClipp** [comment]
I have narrowed down the problem to somewhere in the get_greg function. The problem is that it will sometimes find a beginning gregorian day of 29, while the end it will find to be 30. As an example, let's say that our first Julian value for CERES is:

2456656.958340478

And the end is:

2456656.999992643

These values are from the CERES FM1 2013123011 file.

The get_greg function will find the first time to be day 29, and the second to be day 30. This is incorrect because these two Julian values are obviously the same day, just their fractional component is different. I suspect that this issue is stemming from the fact that 2456656.999992643, when truncated to an integer, will likely become 2456657.

I will not work on this problem any more. Hopefully this information is useful to you.

**Comment by kyang2014** [comment]
Excellent finding, thanks! This is exactly the information I need.

**Comment by kyang2014** [comment]
Landon, Could you point to me where I can find the current input filelist for this orbit?

**Comment by LandonTClipp** [comment]
On Blue Waters:

/u/sciteam/clipp/scratch/inputFiles/2013/input74649.txt

On ROGER, the input file should still exist as I listed in the original post.

**Comment by kyang2014** [comment]
I confirm that the algorithm to convert julian to greg (I got from a java implementation) has an error as Landon found. I am searching on-line and see if I can find a right algorithm. If it doesn't take too long, I will deliver to Landon to implement it.

**Comment by kyang2014** [comment]
Landon, I found a python implementation that gives the correct output for the year, month and day. I will send you an email to you. You can confirm and if it indeed works, convert that implementation to C. First try with a standalone program to test at least a couple of CERES file.  You can also transfer  this task that to other people.

**Comment by LandonTClipp** [comment]
#205
Testing to see if this is fixed.

**Comment by LandonTClipp** [comment]
This has been fixed. The reworked get_greg function works.
