### ISSUE TITLE
List of corrupted files

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#147]
The following files are confirmed to be corrupted. Not sure if these are corrupted from transfer or if files are corrupted originally.

- [x] `/projects/TDataFus/gyzhao/TF/data/ASTER/ASTER_L1T/ASTT/AST_L1T.003/2013.11.24/AST_L1T_00311242013134100_20150618165825_113075.hdf`
- [x] ` /projects/TDataFus/gyzhao/TF/data/ASTER/ASTER_L1T/ASTT/AST_L1T.003/2013.02.03/AST_L1T_00302032013083630_20150614114759_87788.hdf `
- [x] `/projects/TDataFus/gyzhao/TF/data/ASTER/ASTER_L1T/ASTT/AST_L1T.003/2013.04.07/AST_L1T_00304072013124231_20150615070619_8496.hdf `
- [x] `/projects/TDataFus/gyzhao/TF/data/ASTER/ASTER_L1T/ASTT/AST_L1T.003/2013.01.09/AST_L1T_00301092013132753_20150614040715_121242.hdf`
- [x] `/projects/TDataFus/gyzhao/TF/data/ASTER/ASTER_L1T/ASTT/AST_L1T.003/2013.02.22/AST_L1T_00302222013230750_20150614181218_110393.hdf`
- [x] `/projects/TDataFus/gyzhao/TF/data/ASTER/ASTER_L1T/ASTT/AST_L1T.003/2013.02.03/AST_L1T_00302032013080954_20150614114758_42433.hdf`
- [x] `/projects/TDataFus/gyzhao/TF/data/ASTER/ASTER_L1T/ASTT/AST_L1T.003/2013.06.09/AST_L1T_00306092013215538_20150616012212_40427.hdf`
- [x] `/projects/TDataFus/gyzhao/TF/data/ASTER/ASTER_L1T/ASTT/AST_L1T.003/2013.11.24/AST_L1T_00311242013134100_20150618165825_113075.hdf`
- [x] `/projects/TDataFus/gyzhao/TF/data/ASTER/ASTER_L1T/ASTT/AST_L1T.003/2013.12.13/AST_L1T_00312132013073219_20150618231036_44245.hdf`

**Comment by LandonTClipp** [comment]
- [x] /projects/TDataFus/gyzhao/TF/data/ASTER/ASTER_L1T/ASTT/AST_L1T.003/2013.05.19/AST_L1T_00305192013055009_20150615185437_17705.hdf

- [x] /projects/TDataFus/gyzhao/TF/data/ASTER/ASTER_L1T/ASTT/AST_L1T.003/2013.05.19/AST_L1T_00305192013070324_20150615185508_19365.hdf

- [x] /projects/TDataFus/gyzhao/TF/data/ASTER/ASTER_L1T/ASTT/AST_L1T.003/2013.09.19/AST_L1T_00309192013084201_20150617195055_98375.hdf

- [x] /projects/TDataFus/gyzhao/TF/data/ASTER/ASTER_L1T/ASTT/AST_L1T.003/2013.10.09/AST_L1T_00310092013151107_20150618032750_23653.hdf

- [x] /projects/TDataFus/gyzhao/TF/data/ASTER/ASTER_L1T/ASTT/AST_L1T.003/2013.11.01/AST_L1T_00311012013084236_20150618101408_30278.hdf

I found a few more. I see that you have redownloaded the other ones, I will see if that fixes it.

**Comment by LandonTClipp** [comment]
- [x] /projects/TDataFus/gyzhao/TF/data/ASTER/ASTER_L1T/ASTT/AST_L1T.003/2013.05.19/AST_L1T_00305192013070324_20150615185508_19365.hdf
- [x] /projects/TDataFus/gyzhao/TF/data/ASTER/ASTER_L1T/ASTT/AST_L1T.003/2013.05.19/AST_L1T_00305192013084014_20150615185530_106440.hdf
- [x] /projects/TDataFus/gyzhao/TF/data/ASTER/ASTER_L1T/ASTT/AST_L1T.003/2013.06.09/AST_L1T_00306092013215316_20150616012132_38546.hdf
- [x] /projects/TDataFus/gyzhao/TF/data/ASTER/ASTER_L1T/ASTT/AST_L1T.003/2013.06.29/AST_L1T_00306292013132358_20150616075232_116895.hdf
- [x] /projects/TDataFus/gyzhao/TF/data/ASTER/ASTER_L1T/ASTT/AST_L1T.003/2013.07.18/AST_L1T_00307182013121915_20150616141124_103849.hdf

That should be the last of it for 2013.

**Comment by sandman0o0** [comment]
Those should be all set.
