### ISSUE TITLE
CERES failed to retrieve orbit info

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#149]
Using `/projects/TDataFus/fusionTesting/input/2013/input72631.txt`, the following error occurs:

```
[./src/CERES.c:1240] Fatal error: The UTC time retrieved from CERES array is out of range
[./src/CERES.c:1054] Fatal error: Obtain_start_end_index: Failed to obtain the start and end index.
[./src/main.c:453] Fatal error: CERES failed to obtain orbit info.
Exiting program.
```

I will update this error as I investigate it more.

**Comment by kyang2014** [comment]
oribit info:
72631 2013-08-13T20:59:53Z 2013-08-13T22:38:46Z
Found the issue, The second can be greater than 59. I think in theory the minute/hour can also be 60.

**Comment by kyang2014** [comment]
Landon, I think I fixed this issue. However the change(CERES.c) is at the branch temp_aster_fix(for convenient). Please merge them to the master.

**Comment by LandonTClipp** [comment]
Okay, I will merge that into master. I'd like this branch to be frozen, doing any merges with master will likely result in conflicts. More fixes should be done on a new branch. Thanks for finding the bug.
