### ISSUE TITLE
MODIS unable to open 500m file

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#151]
Using input73103.txt, the following error occurs:

```
[./src/MODIS.c:178] Fatal error: Unable to open 500m file.
[./src/main.c:684] Fatal error: MODIS failed data transfer.
Exiting program.
```

**Comment by kyang2014** [comment]
The file is corrupted.

**Comment by LandonTClipp** [comment]
@kyang2014 
My suggestion is related to #165: if the BF program encounters an issue like this (recall, in this case the HDF file was really a metadata file), it should not be a fatal error but rather the BF program should skip it and move on. Thoughts?

**Comment by kyang2014** [comment]
No, we should make it a fatal error now to make the information stand out. Skipping files may be necessary in the future if we know that file simple doesn’t exist.

**Comment by LandonTClipp** [comment]
Closing this issue. We have logged corrupt or zero files.
