### ISSUE TITLE
Write script that gives number of output files that are in a given range

### ISSUE THREAD

**Issue by kyang2014** [TerraFusion/basicFusion#156]
> 100GB
80 GB < file size < 100 GB
60 GB < file size < 80 GB
40 GB < file size < 60 GB
20 < file size < 40 GB
10 < file size < 20 GB
1 GB < file size < 10 GB
100MB < file size < 1GB
10MB < file size < 100MB
1 MB < file size < 10MB
file size < 1 MB

Attach file name to this information

**Comment by kyang2014** [comment]
Also for input hdf files, find all files with size < 2MB. Generate output.

**Comment by LandonTClipp** [comment]
/projects/TDataFus/fusionTesting/output/2013

**Comment by LandonTClipp** [comment]
Results:

> [clipp@cg-gpu01 util]$ ./fileSizeNum.sh /projects/TDataFus/fusionTesting/output/2013
> file size > 100GB: 92
> 80GB < file size < 100GB: 496
> 60GB < file size < 80GB: 1587
> 40GB < file size < 60GB: 2667
> 20GB < file size < 40GB: 30
> 10GB < file size < 20GB: 9
> 1GB < file size < 10GB: 2
> 100MB < file size < 1GB: 0
> 10MB < file size < 100MB: 4
> 1M < file size < 10MB: 148
> file size < 1MB: 0

**Comment by kyang2014** [comment]
Great. Could you give me the total size of all output files? Thanks,

**Comment by LandonTClipp** [comment]
All the 2013 output files are 302TB.
