### ISSUE TITLE
Check MODIS file continuity

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#157]
Check that all MODIS files in database are all 5 minutes apart. Log any MODIS files that are found missing.

https://github.com/TerraFusion/basicFusion/blob/master/inputFileDebug/roger_large_input.txt

For MODIS 1KM files:
```
/projects/TDataFus/gyzhao/TF/data/MODIS/MOD021KM
```

For MODIS MOD03 files:
```
/projects/TDataFus/gyzhao/TF/data/MODIS/MOD03
```

**Comment by shashankbansal6** [comment]
[MODIS_Continuity_Check_MOD03_2001.txt](https://github.com/TerraFusion/basicFusion/files/1093111/MODIS_Continuity_Check_MOD03_2001.txt)
[MODIS_Continuity_Check_MOD03_2002.txt](https://github.com/TerraFusion/basicFusion/files/1093113/MODIS_Continuity_Check_MOD03_2002.txt)
[MODIS_Continuity_Check_MOD03_2003.txt](https://github.com/TerraFusion/basicFusion/files/1093112/MODIS_Continuity_Check_MOD03_2003.txt)
[MODIS_Continuity_Check_MOD03_2004.txt](https://github.com/TerraFusion/basicFusion/files/1093114/MODIS_Continuity_Check_MOD03_2004.txt)
[MODIS_Continuity_Check_MOD03_2005.txt](https://github.com/TerraFusion/basicFusion/files/1093116/MODIS_Continuity_Check_MOD03_2005.txt)
[MODIS_Continuity_Check_MOD03_2006.txt](https://github.com/TerraFusion/basicFusion/files/1093115/MODIS_Continuity_Check_MOD03_2006.txt)
[MODIS_Continuity_Check_MOD03_2007.txt](https://github.com/TerraFusion/basicFusion/files/1093121/MODIS_Continuity_Check_MOD03_2007.txt)
[MODIS_Continuity_Check_MOD03_2008.txt](https://github.com/TerraFusion/basicFusion/files/1093117/MODIS_Continuity_Check_MOD03_2008.txt)
[MODIS_Continuity_Check_MOD03_2009.txt](https://github.com/TerraFusion/basicFusion/files/1093122/MODIS_Continuity_Check_MOD03_2009.txt)
[MODIS_Continuity_Check_MOD03_2010.txt](https://github.com/TerraFusion/basicFusion/files/1093119/MODIS_Continuity_Check_MOD03_2010.txt)
[MODIS_Continuity_Check_MOD03_2011.txt](https://github.com/TerraFusion/basicFusion/files/1093118/MODIS_Continuity_Check_MOD03_2011.txt)
[MODIS_Continuity_Check_MOD03_2012.txt](https://github.com/TerraFusion/basicFusion/files/1093120/MODIS_Continuity_Check_MOD03_2012.txt)
[MODIS_Continuity_Check_MOD03_2013.txt](https://github.com/TerraFusion/basicFusion/files/1093123/MODIS_Continuity_Check_MOD03_2013.txt)
[MODIS_Continuity_Check_MOD03_2014.txt](https://github.com/TerraFusion/basicFusion/files/1093124/MODIS_Continuity_Check_MOD03_2014.txt)
[MODIS_Continuity_Check_MOD03_2015.txt](https://github.com/TerraFusion/basicFusion/files/1093126/MODIS_Continuity_Check_MOD03_2015.txt)
[MODIS_Continuity_Check_MOD03_2016.txt](https://github.com/TerraFusion/basicFusion/files/1093127/MODIS_Continuity_Check_MOD03_2016.txt)
[MODIS_Continuity_Check_MOD021KM_2000.txt](https://github.com/TerraFusion/basicFusion/files/1093125/MODIS_Continuity_Check_MOD021KM_2000.txt)
[MODIS_Continuity_Check_MOD021KM_2001.txt](https://github.com/TerraFusion/basicFusion/files/1093128/MODIS_Continuity_Check_MOD021KM_2001.txt)
[MODIS_Continuity_Check_MOD021KM_2002.txt](https://github.com/TerraFusion/basicFusion/files/1093129/MODIS_Continuity_Check_MOD021KM_2002.txt)
[MODIS_Continuity_Check_MOD021KM_2003.txt](https://github.com/TerraFusion/basicFusion/files/1093134/MODIS_Continuity_Check_MOD021KM_2003.txt)
[MODIS_Continuity_Check_MOD021KM_2004.txt](https://github.com/TerraFusion/basicFusion/files/1093130/MODIS_Continuity_Check_MOD021KM_2004.txt)
[MODIS_Continuity_Check_MOD021KM_2005.txt](https://github.com/TerraFusion/basicFusion/files/1093131/MODIS_Continuity_Check_MOD021KM_2005.txt)
[MODIS_Continuity_Check_MOD021KM_2006.txt](https://github.com/TerraFusion/basicFusion/files/1093132/MODIS_Continuity_Check_MOD021KM_2006.txt)
[MODIS_Continuity_Check_MOD021KM_2007.txt](https://github.com/TerraFusion/basicFusion/files/1093133/MODIS_Continuity_Check_MOD021KM_2007.txt)
[MODIS_Continuity_Check_MOD021KM_2008.txt](https://github.com/TerraFusion/basicFusion/files/1093136/MODIS_Continuity_Check_MOD021KM_2008.txt)
[MODIS_Continuity_Check_MOD021KM_2009.txt](https://github.com/TerraFusion/basicFusion/files/1093135/MODIS_Continuity_Check_MOD021KM_2009.txt)
[MODIS_Continuity_Check_MOD021KM_2010.txt](https://github.com/TerraFusion/basicFusion/files/1093137/MODIS_Continuity_Check_MOD021KM_2010.txt)
[MODIS_Continuity_Check_MOD021KM_2011.txt](https://github.com/TerraFusion/basicFusion/files/1093138/MODIS_Continuity_Check_MOD021KM_2011.txt)
[MODIS_Continuity_Check_MOD021KM_2012.txt](https://github.com/TerraFusion/basicFusion/files/1093141/MODIS_Continuity_Check_MOD021KM_2012.txt)
[MODIS_Continuity_Check_MOD021KM_2013.txt](https://github.com/TerraFusion/basicFusion/files/1093139/MODIS_Continuity_Check_MOD021KM_2013.txt)
[MODIS_Continuity_Check_MOD021KM_2014.txt](https://github.com/TerraFusion/basicFusion/files/1093142/MODIS_Continuity_Check_MOD021KM_2014.txt)
[MODIS_Continuity_Check_MOD021KM_2015.txt](https://github.com/TerraFusion/basicFusion/files/1093140/MODIS_Continuity_Check_MOD021KM_2015.txt)
[MODIS_Continuity_Check_MOD021KM_2016.txt](https://github.com/TerraFusion/basicFusion/files/1093143/MODIS_Continuity_Check_MOD021KM_2016.txt)

**Comment by LandonTClipp** [comment]
@sandman0o0 These are some more missing files. Are the error logs in these files in a format that is useful to you? There are quite a lot...

**Comment by sandman0o0** [comment]
That format should work... Easy enough tonparse out what I need.

**Comment by shashankbansal6** [comment]
The formatting is:
1. The missing files.
2. The missing dates.
3. The zero size files.

**Comment by rccm** [comment]
You can merge all the Continuity_Check text files into one. Add "*" at the end of each line that contains the MODIS file names (partially). Then upload the text files on the LAADS data searching website: https://ladsweb.modaps.eosdis.nasa.gov/search/locate 
If no results returns, that means these missing files are also missing at the DAAC.
