### ISSUE TITLE
Check all granules for corrupt files

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#158]
Parse all input HDF files, using the tool "hdp  " to see if the file is corrupted. If the file is corrupted, log it.

Do the following:
hdp dumpsds -h "HDF4filename"

If the output is something like HDP ERROR>>> in do_dumpsds: dsd failed.
The file must not be a valid HDF4 file. We can label it as a corrupted file.

You can easily check the size of the output. With normal HDF4 file, it should be greater than 500 bytes. For the corrupted file, the output will be smaller than that.

**Comment by shashankbansal6** [comment]
I am working on it. I have written the script but the script is taking too long to run so I need to parallelize the code and run it on ROGERS.

**Comment by LandonTClipp** [comment]
Let me know when you are ready for me to help you with establishing parallel workflow.

**Comment by shashankbansal6** [comment]
These are the lists of all the corrupt files in MODIS for the year 2013 for Half Kilometer. There are no corrupt files for 1 kilometers.

[MODIS_Corrupt_Check_MOD02HKM_2013_2.txt](https://github.com/TerraFusion/basicFusion/files/1106496/MODIS_Corrupt_Check_MOD02HKM_2013_2.txt)
[MODIS_Corrupt_Check_MOD02HKM_2013_4.txt](https://github.com/TerraFusion/basicFusion/files/1106498/MODIS_Corrupt_Check_MOD02HKM_2013_4.txt)
[MODIS_Corrupt_Check_MOD02HKM_2013_5.txt](https://github.com/TerraFusion/basicFusion/files/1106500/MODIS_Corrupt_Check_MOD02HKM_2013_5.txt)
[MODIS_Corrupt_Check_MOD02HKM_2013_7.txt](https://github.com/TerraFusion/basicFusion/files/1106499/MODIS_Corrupt_Check_MOD02HKM_2013_7.txt)
[MODIS_Corrupt_Check_MOD02HKM_2013_9.txt](https://github.com/TerraFusion/basicFusion/files/1106497/MODIS_Corrupt_Check_MOD02HKM_2013_9.txt)

**Comment by LandonTClipp** [comment]
This is closed in favor of #208
