### ISSUE TITLE
Discussion: Should we really assume that any cameras are present?

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#163]
I have been thinking about the way we have been writing the code. Currently we assume that all Terra cameras that are currently operational (as of 2017) must always be represented. For instance, MISR has 9 different cameras:

AA, AF, AN, BA, BF, CA, CF, DA, DF.

I am hesitant to write the assumption in our code that these files must always exist (this is how the code is currently written). Terra instruments have a history of shutting certain cameras down when they become dysfunctional. As far as future regenerations of Basic Fusion files, assuming that any camera exists seems risky to me.

This is just a low priority topic, something to think about.

**Comment by rccm** [comment]
So far, I have not seen any cases where only some of the MISR nine cameras shut down, although theoretically this is possible. Please let me know if you find one.
