### ISSUE TITLE
Update and re-ingest collection metadata.

### ISSUE THREAD

**Issue by hyoklee** [TerraFusion/basicFusion#189]
Guangyu updated collection metadata in MS word online. Please update 
[sample_echo10.xml](https://github.com/TerraFusion/basicFusion/blob/master/CMR/sample_echo10.xml) accordingly. I'll send the link via email.

**Comment by richielo** [comment]
Updated the sample_echo10.xml and ingested it to the server. I also updated the ingestion script so it uses the DataSetId as native-id during ingestion

**Comment by hyoklee** [comment]
I can check the updated metadata from search.uat.earthdata.nasa.gov.
