### ISSUE TITLE
Test Image Check scripts

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#255]
Thorough checks need to be performed on the code on @richielo 's image verification branch. I initially rejected his pull request until these codes can be confirmed to be functional.

**Comment by LandonTClipp** [comment]
@shashankbansal6 Please acclimate yourself to 21f65bb1c8714f97091a8ed393fbd16f60b26194 and perform tests on it. Need to make sure that the MPI code works before we commit to master branch.

**Comment by richielo** [comment]
Hi @LandonTClipp  @shashankbansal6 , I should be relatively less occupied in the coming few weeks after I overcome  the horrible jetlag. I would  like to finish the MPI part(at least making it functional), if you guys don't mind. If not, I am always active here if any help is needed from me. Cheers

**Comment by LandonTClipp** [comment]
Hi Richie, hope your flight was okay! You can certainly work on this part, especially considering you wrote it. I'll assign this to you for now.
