### ISSUE TITLE
BF Workflow Bug Report

### ISSUE THREAD

**Issue by shashankbansal6** [TerraFusion/basicFusion#264]
When I run` ./configureEnv.sh -a` , I get an error. 
`./configureEnv.sh: line 16: virtualenv: command not found`

**Comment by LandonTClipp** [comment]
This comment will keep track of the TODO for these bug reports.

- [ ] virtualenv not found is due to python 2.7 not being loaded as a module. Indicate in README for user to load this, or perhaps have script automatically load it. For now, manually load Python 2.7.
