### ISSUE TITLE
Fix tar files

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#309]
- [x] 40422 Has GMP files included twice. _**Fix transferred to Nearline (March 5 2018).**_
- [x] 37408 Identified MISR_AA file as corrupt. Removed file from tar. _**Fix transferred to Nearline (March 5 2018)**_
- [x] 21232 Identified MISR_AM1_GRP_ELLIPSOID_GM_P175_O021232_BF_F03_0024.hdf as corrupt. _**Fix transferred to Nearline (March 5 2018)**_
- [x] 33889 Identified MOD02QKM.A2006122.1210.006.2014228111426.hdf as corrupt. Removed file from tar. _**Transferred to Nearline (March 6 2018).**_
- [x] 13659 Queried SQLite DB for correct files from Condo. Pulled from condo, manually generated tar (same structure as all others). _**Transferred to Nearline (March 6 2018).**_
- [x] 13660. MISR_PATH file was simply never created. Manually created MISR_PATH and re-tarred all Terra files. _**Transferred to Nearline (March 8 2018)**_

**Comment by kyang2014** [comment]
The MODIS file at 33889 was re-downloaded after you transferred the original corrupt one to nearline. So don't remove that file and changed the tar file. Just transfer this file from condo to nearline.

**Comment by LandonTClipp** [comment]
I redownloaded the file from condo, retarred and sent back to Nearline. Hopefully now this is correct.

**Comment by kyang2014** [comment]
The inputfile at 37408 is not fixed. The corrupt AA file is still listed there.

**Comment by LandonTClipp** [comment]
I will try to fix this in a few minutes. Not sure why that is still there.

**Comment by LandonTClipp** [comment]
The file was accidentally misnamed when I initially transferred it. Used same mispelling when I initially verified file. I pushed back the correct name and confirmed it to be correct.

**Comment by LandonTClipp** [comment]
Orbit 13659 does not seem to be on Nearline. Have you re-processed this one?

**Comment by kyang2014** [comment]
13659 as well other 5 troubled orbits were reprocessed.

Check them under /u/sciteam/ymuqun/scratch/bf_workflow/BFoutput

On Mar 15, 2018, at 11:19 AM, Landon Clipp <notifications@github.com<mailto:notifications@github.com>> wrote:


Orbit 13659 does not seem to be on Nearline. Have you re-processed this one?
