### ISSUE TITLE
Memory leaking

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#31]
CERES is leaking memory on BW when running unpacking. Need to run the program with same input on ROGER to see if leak persists. It's strange that CERES leaks during unpacking but not during no unpacking because CERES does not unpack ever.

ASTER is also leaking during unpacking.

Goal is to submit valgrind output for both BW and ROGER for the same input to compare the difference (if there is any).

**Comment by kyang2014** [comment]
Landon,  once you run the same code at roger with valgrind, provide the valgrind output.

**Comment by kyang2014** [comment]
Hint:
1) Only the CERES leak was observed when the  at Roger when I checked the big enhancement code at https://github.com/TerraFusion/basicFusion/commit/58035b195802b488149134435a6d9cfc3e127e7b on Dec. 21st. The ASTER leak(a more severe leak) was introduced in the code checked in later.
2) The brief check of the ASTER code leak doesn't show obvious leaking. The data allocated is freed.

**Comment by LandonTClipp** [comment]
I will run more valgrind jobs on BW to do more memory debugging. I'll do some on ROGER tomorrow when it is back online.

**Comment by kyang2014** [comment]
Landon, have you run valgrind jobs on both BW and roger regarding this?

**Comment by LandonTClipp** [comment]
Dr. Yang, please refer to my email I have sent you. I have not completed this step yet.

**Comment by kyang2014** [comment]
I start checking this at roger. Still see valgrind memory leaking issues.

**Comment by kyang2014** [comment]
ASTER memory leaking is fixed. There is still  a small leaking for CERES. Still to check.

**Comment by kyang2014** [comment]
The leaking is from MISR. The CERES message is fake.  One API handle is not closed when breaking the for loop. 

https://github.com/TerraFusion/basicFusion/commit/5907e41a7b44348573bbb3e40ba61cb4e907c8be
