### ISSUE TITLE
Need to finish the sha256sum for some orbits

### ISSUE THREAD

**Issue by kyang2014** [TerraFusion/basicFusion#312]
1. Need to pull from nearline to calculate the checksum for the following orbits:
1000-21474(year 2000-2003)
78000-83999

2. Also there are overlaps between Kent and Landon's BF generations. The following orbits are overlapped:
40282-40782
Landon needs to check which BF files Landon picked up to push to nearline. The checksum should be the ones at nearline. Needs to confirm!

3. Between 1000-21474, there are 3 BF files currently we are calculating sha256sum now. These check sums can be used to see if our second round of checksum is right.
They are orbit 13659,13660 and 21232. 

4. Under /u/sciteam/ymuqun/scratch/BF_new_workflow/BFoutput/2000/02/25
You can find BF files for orbit 1000 and 1001. The checksum of these files should be discarded since these files were generated to test the update of workflow scripts at that time.

**Comment by LandonTClipp** [comment]
2. My generation for the overlapped orbits is logged here:
`/u/sciteam/clipp/basicFusion/util/TerraGen/BF_jobFiles/run23/`
It pushed the overlapped orbits on Feb 23, but the modification time of the files on NL are March 1, so the files pushed must have been from @kyang2014.

**Comment by LandonTClipp** [comment]
I have obtained a listing of all the files on NL that we need a checksum for. I am pinging Sean again about this and have sent him the list. Hopefully NCSA will respond soon. If not, I am going to begin doing the checksum myself (this is not the ideal scenario).

**Comment by kyang2014** [comment]
Landon,
As we discussed, we need to do the checksum by ourselves regardless of what NCSA can do. You’ve done most of them already. Why did you change your mind?

**Comment by LandonTClipp** [comment]
You are correct, I needed to review our meeting notes. This is what I will do. I am starting this process now.

**Comment by LandonTClipp** [comment]
The process has started for generating the checksums of the missing orbits. Currently generating 5000 checksums out of 27972.

**Comment by kyang2014** [comment]
@LandonTClipp 
It seems that you finish this ticket. Can we close it?

**Comment by LandonTClipp** [comment]
We can close this as well.
