### ISSUE TITLE
Backup input granules 

### ISSUE THREAD

**Issue by kyang2014** [TerraFusion/basicFusion#313]
- [x] Start transferring MOD03 files  right now from condo to  BW scratch if that's all left for MODIS.
- [x] Start transferring year 2015 input granules(for all five instruments) from condo to nearline since we don't have any copy for year 2015.
- [x] Wait until next Monday(April 2nd) to see if we need to transfer MISR files from condo to BW scratch or from condo to nearline. No matter which route to go, we need to start from the second half mission.

**Comment by LandonTClipp** [comment]
Having problem with condo, my credentials are invalid??? Contacting JD about this.

**Comment by LandonTClipp** [comment]
Fixed problem with condo. Started transfer of all instruments year 2015 from ncsa#terra to ncsa#nearline, except for MODIS (which is being transferred to scratch instead).

Also, I had forgotten that all MISR 2007-2015 is already on Nearline! That was done two months ago in February.

**Comment by LandonTClipp** [comment]
@kyang2014 NCSA Emailed me about the ASTER transfer from Condo --> Nearline. Said that the extremely large number of files will make it nearly impossible to retrieve ASTER from Nearline, recommended we tar beforehand.

**Comment by kyang2014** [comment]
I assume it only applies to year 2015? If we can tar ASTER at condo, it is OK to do that. Will they extend the deadline for us to tar the files and then transfer to nearline?
Make sure we transfer all other files from condo to nearline in the mean time.

**Comment by LandonTClipp** [comment]
I will talk to JD about this and see if we can. I remember him saying that he can create an filesystem mount from condo to Nebula.

**Comment by kyang2014** [comment]
The bottom-line is to make sure all input granules are transferred out of condo before they are removed. If we have difficulty in achieving this goal, we should let Larry know immediately.

**Comment by LandonTClipp** [comment]
So this is the current status:

- MODIS will be fine. Resides at scratch. Needs to be tarred if put onto NL. ~280,000 files per year!
- MISR will be fine, we have all granules on NL (second half was transferred by me two months ago)
- MOPITT will be fine, on NL
- CERES is fine, on NL. May be difficult to manage because there are ~40,000 files per year.
- ASTER 2015 needs to be tarred somehow. There are 200,000 files just for one year!!!

**Comment by kyang2014** [comment]
Is it possible to transfer this 2015 ASTER and CERES files to BW for you to tar? If doable,  I will  say, transferring CERES first since it is small. Once we got all the second-half mission BF validated /updated, we should have plenty space to host 2015 ASTER. My biggest concern is the time, do we have enough time to handle this before the deadline (June 4th, 2018, 2 months from now)?

**Comment by kyang2014** [comment]
Landon,

From your latest email, it seems that you finished all the data transfer from condo. Could you update this ticket? Also could you provide the latest status for the data transfer from scratch to nearline?

**Comment by LandonTClipp** [comment]
The following data products are either on scratch or nearline:

- AST_L1T.003
- CERES FM1 SSF
- CERES FM2 SSF
- MISR AGP
- MISR AGPHR
- MI1B2E.003
- MIB2GEOP.003
- MOD021KM
- MOD02HKM
- MOD02QKM
- MOD03
- MOP01.007

This includes all years 2000 through 2015.

The following data is on Nearline in tar format:
- AST_L1T.003: 2000, 2002-2007, 2009-2015
- MI1B2E 2015, 2014
- All MODIS products: 2007-2015

I am still in the process of tarring the rest of the products and pushing them to NL. I remove products from scratch once they have been transferred to NL.

**Comment by LandonTClipp** [comment]
All L1B granules are on Nearline
