### ISSUE TITLE
Obtain the sha256 checksum for all 84303 BF files

### ISSUE THREAD

**Issue by kyang2014** [TerraFusion/basicFusion#315]
1) First handle #312 by pulling 500 or 1000 BF files once and calculating sha256sum. 
2) Check if we have all  the 84303 sha256sum files for orbit 1000 to 85302.
3) Add any missing sha256sum.
4) Combine all 84303 checksum into one text file with the format <TF file name, sha256sum value> for each line.

**Comment by LandonTClipp** [comment]
Checksumming has been completed. Now working on combining checksums into one file.

**Comment by LandonTClipp** [comment]
All checksums have been combined into a single file. Pushing this file to nearline.
