### ISSUE TITLE
Check the organization of BF files under scratch

### ISSUE THREAD

**Issue by kyang2014** [TerraFusion/basicFusion#316]
We need to have the final layout of BF files under scratch.
Here are Kent's BF file location:
2004 and 2005 under /u/sciteam/ymuqun/scratch/bf_workflow/BFoutput
These BF files are reserved for the team to use. They should not be purged.
I still keep 1002 BF files under /u/sciteam/ymuqun/scratch/BF_new_workflow/BFoutput/2000
and /u/sciteam/ymuqun/scratch/BF_new_workflow/BFoutput/2011
These can be removed if necessary.  The total size I am using is around 330 TB.

Landon needs to have an inventory of the BF files and the total size under his directory and report here.
I need to share the information with other team members.

**Comment by LandonTClipp** [comment]
Here is my current scratch.

3.4T    ./missing
1.5G    ./48000_49999
1.7G    ./80000_83999
1.6G    ./60000_61999
1.6G    ./64000_65999
1.6G    ./72000_73999
14G     ./55559
1.6G    ./76000_77999
48T     ./52000_53999
351G    ./MISR_PATH
48T     ./56000_57999
48T     ./54000_55999
1.5G    ./50000_51999
984G    ./misr_53197_55998
484T    ./terra_L1B
1.5G    ./68000_69999
882M    ./43000_43999
744M    ./63000_63999
1.6G    ./78000_79999
122T    ./bf_hashing
978M    ./reprocess
1.4G    ./46000_47999
1.5G    ./44000_45999
1.5G    ./58000_59999
1.5G    ./70000_71999
1.6G    ./74000_75999
3.6T    ./misr_62000_62999
1.6G    ./66000_67999
756T    .
756T    total

**Comment by LandonTClipp** [comment]
Note: It seems to me that it may be better if we simply re-download a year of BF data from NL instead of worrying about combining what we have on scratch. Downloading the year will only take about a week, that does not seem that unreasonable to me. This will be less work for us too.

**Comment by kyang2014** [comment]
Landon,
You don't need to re-download or combine any BF files. This is simply for information sharing. If we need to clean up some space for other people to use, we can remove all the BF files except year 2004 and 2005. Before doing that, we need to tell them what BF files we need to clean. That's all.

**Comment by LandonTClipp** [comment]
Thanks Dr. Yang.

I would like to clear up the BF files I have on scratch right now. This will help speed up my checksumming work, I have to keep stopping my NL transfers because of hitting the scratch quota.

**Comment by kyang2014** [comment]
That is a good plan.
On Apr 19, 2018, at 2:25 PM, Landon Clipp <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks Dr. Yang.

I would like to clear up the BF files I have on scratch right now. This will help speed up my checksumming work, I have to keep stopping my NL transfers because of hitting the scratch quota.

**Comment by kyang2014** [comment]
@LandonTClipp 
I think you've gotten this under control. Can we close this ticket?

**Comment by LandonTClipp** [comment]
Yes we can close this ticket. I will do that now.
