### ISSUE TITLE
Back up  the input granules at nearline

### ISSUE THREAD

**Issue by kyang2014** [TerraFusion/basicFusion#317]
have already had a ticket #313,  Besides #313, a few observations and tasks:
1) I haven't found any MODIS 2015 files under 
/projects/sciteam/bage/terraL1B/MODIS
Where are MODIS?
2) Tar ASTER files at scratch and back up them at nearline
3) Carefully examine if we have all input granules backed up at nearline.

**Comment by LandonTClipp** [comment]
All of MODIS is on scratch right now. I have not moved these to NL yet because there are a large number of files.

**Comment by kyang2014** [comment]
You need to do this ASAP either by tarring them or untarring them. We are not sure how long we can have this 1.3 PB.

**Comment by LandonTClipp** [comment]
I am tarring the ASTER 2015 right now. This should take about an hour.

**Comment by LandonTClipp** [comment]
MODIS 2015 is being tarred right now.

**Comment by LandonTClipp** [comment]
All granules on NL
