### ISSUE TITLE
Save all the metadata-related information to nearline

### ISSUE THREAD

**Issue by kyang2014** [TerraFusion/basicFusion#319]
The information includes 
1) the CDL etc. information for the second mission. Those should be under Landon's /u/sciteam/clipp/scratch sucn as 43000_43999. 
2) Kent's validation metadata reference
 kent_re-process-out.tar.gz under /u/sciteam/ymuqun/scratch
kent_valid_output.tar.gz under /u/sciteam/ymuqun/scratch

**Comment by LandonTClipp** [comment]
All of these files have been transferred to NL. I will write up a document describing this now.
