### ISSUE TITLE
Correct name function (Jan 13th)

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#32]
To follow the CF conventions, object names should include alphanumeric and underscore characters. The first character of the name should not be a number.   Follow the function H4toH5correctname
(Line 6169, https://bitbucket.hdfgroup.org/projects/HDFEOS/repos/h4h5tools/browse/lib/src/h4toh5eos.c) to implement

Action: Implement by Jan. 13th, 2017
Status: TODO

**Comment by LandonTClipp** [comment]
I was unable to use the provided code in bitbucket because it introduced some structs and functions that I do not have and could not find. More specifically, the use of challoc. I did expand the existing correct_name function to follow all of the conventions in that function. @kyang2014 I need to know if this is okay. If not, I will need to include the challoc definitions somehow.

**Comment by kyang2014** [comment]
I am not asking you to copy and paste the whole function. I just ask you to revise it. Challoc function is just a wrapper. You should not use it. It should be straightforward for you to use malloc.  I still prefer to follow the bitbucket code since it is well tested.

**Comment by LandonTClipp** [comment]
Okay that is good. I will revise what I've written to follow the function
structure closely.

**Comment by LandonTClipp** [comment]
Function has been implemented

**Comment by kyang2014** [comment]
The way to use the correct_name function at MISR data is wrong. In MISR.c
 correctedName = correct_name(radiance_name[j]);

                h5DataFieldID =  readThenWrite( h5DataGroupID, correctedName, DFNT_UINT16,
                                                H5T_NATIVE_USHORT,h4FileID);

The HDF4 object name should not be changed. Only HDF5 names should be corrected. I will fix this.

**Comment by LandonTClipp** [comment]
I have modified readThenWrite to update a pointer given to it to point to
the output HDF5 name. I did this because I was having difficulties writing
attributes to the HDF5 objects because I did not know what their output
name was (as input and output names cannot be guaranteed to be the same).

**Comment by LandonTClipp** [comment]
Correction, I updated the MISR unpack function to do such a thing. You are
right that what I have there is wrong.

On Jan 26, 2017 10:26 AM, "Landon Clipp" <clipp2@illinois.edu> wrote:

I have modified readThenWrite to update a pointer given to it to point to
the output HDF5 name. I did this because I was having difficulties writing
attributes to the HDF5 objects because I did not know what their output
name was (as input and output names cannot be guaranteed to be the same).

**Comment by kyang2014** [comment]
Hopefully you understand the issue already. Just in case.
The main problem is not in the unpack part. It is in the pack part.
This is in the code at https://github.com/TerraFusion/basicFusion/blob/develop/src/MISR.c

Between Line 186 and 196.
// For packed you should not correct the object name first. You should only correct it when writing an HDF5 dataset.

else {



correctedName = correct_name(radiance_name[j]);






h5DataFieldID = readThenWrite( h5DataGroupID, correctedName, DFNT_UINT16,



H5T_NATIVE_USHORT,h4FileID);



if ( h5DataFieldID == EXIT_FAILURE )



{



h5DataFieldID = 0;



FATAL_MSG("MISR readThenWrite function failed.\n");



goto cleanupFail;



}


}

**Comment by kyang2014** [comment]
I just corrected the usage and assigned the ticket to myself.

**Comment by kyang2014** [comment]
Resolved it. https://github.com/TerraFusion/basicFusion/commit/825add31565424bbbba99830709558c59772727f
