### ISSUE TITLE
Add dimension scales to our datasets (Jan 31)

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#35]
Add dimension scales to our datasets.
Find the MOPITT dimensions in the original HDF-EOS5 file and hardcode in the software package 
Dimension information can be found inside the StructMetadata.0.  Find the group dimension and you can find the dimension names etc. The meaning of dimensions can be found at   http://www.acom.ucar.edu/mopitt/file-spec.shtml#L1

CERES- No dimension names are stored in the HDF file. So we need to use the fakeDim?? generated by HDF4. If we find the dimension information in the document, we should use those information. 
**_UPDATE: the CERES file has dimension names. So use the dimension name instead.** 
MISR MODIS and ASTER can use  HDF4 SD interface to retrieve the dimension scale.
For the dimension that doesn’t have a dimension scale(most of our cases), 
Use netCDF attribute name to identify the pure dimension, check the routine change_dim_attr_NAME_value
at https://bitbucket.hdfgroup.org/projects/HDFEOS/repos/h4h5tools/browse/lib/src/h4toh5sds.c

H5DSattach_scale and H5DSset_scale routines need to be used to generate the dimension scale HDF5 dataset and attach the dimension scales to an HDF5 dataset.

Handle_general_dim_scale: You can find how to use H5DSattach_scale
Create_general_dim_scale: You can find how to use H5DSset_scale
         A MODIS example for illustration:
SD interface to retrieve dimension information. 
H5DSset_scale for the dimensions. Apply change_dim_attr_NAME_value to follow the netCDF conventions.
H5DSattach_scale for the HDF5 dataset, in this example, EV_REF1B?

**ACTION**: 

- [x] Understand the concept and implement one example(MODIS). Create a new branch. The first implementation of one instrument by Feb. 10th. Will brief Kent by Jan. 31st.

- [ ] Need to identify all dimension scales that require scale information. Where to find that scale information if not provided by the input HDF files?

 
- [ ] Pending further information about what other datasets need dimension scales

**Completed Instruments**

- MODIS
- CERES (still need to add CERES dimension names)
- ASTER
- MISR
- MOPITT

**Comment by LandonTClipp** [comment]
@kyang2014 

I am still trying to understand how dimension scales work. I am working on the MODIS example and I have a few questions that I need answered. What I don't understand what I need to do is what information from the original HDF4 dimension scale I need to copy over to the corresponding HDF5 dimension scale. I understand the HDF4 API for accessing a dimension but I don't understand what I need to do to correctly copy this over to HDF5.

I am also confused about how to actually create an HDF5 dimension scale. The function H5Dset_scale converts the dataset to a dimension scale, but after that I do not see any H5DS functions that allow modification of those scales. Am I supposed to apply H5Dset_scale to the entire datasets that we currently have in our output HDF5 file or are dimension scales created by first creating one dataset (that represents a single dimension), converting it to a dimension scale, and then attaching it a dimension in the final dataset? I believe the latter is what I actually need to do but there is still a lot I don't understand.

Here is the crux of what I don't understand:
1. Are dimension scales actually represented as datasets? 
2. If 1 is true, then what I must do is read the dimension scale dataset from HDF4 into a buffer and then create a new HDF5 dataset, copying the buffer into that dataset, converting that dataset into an HDF5 dimension scale, and finally attaching that dimension scale to a specific dimension in the output dataset. Am I understanding this correctly?

While I wait for your response, I will continue trying to implement the MODIS example.

**Comment by LandonTClipp** [comment]
@kyang2014 

I have come up with another question:

The function SDdiminfo (which I am using to get dimension name, size and number type) returns an HDF4 number type for the dimension. In order to create the dimension in HDF5 I need some kind of mapping from HDF4 type to HDF5 type (as you know, the representations for number types are not inter-compatible between 4 and 5). Should I just assume the number type for our program or can I somehow use a portion of your "h4type_to_h5type" function for the mapping?

**Comment by kyang2014** [comment]
See the inserted.
________________________________

**Comment by kyang2014** [comment]
Yes, you can use it. Make sure you add the source of that function and add HDF copy right to it.


________________________________

**Comment by LandonTClipp** [comment]
I have adapted the h4type_to_h5type to our program however it is not behaving as expected. I will need to fix that. I have added code to convert one single dimension to a dimension scale, but because the conversion function doesn't work I have not been able to get it to work just yet. I believe I have a decent understanding of how dimension scales are supposed to work. I expect the first example to be done this weekend.

**Comment by kyang2014** [comment]
AFAIK, h4type_to_h5type should work since h4toh5 conversion tool has been around for >15 years and has been tested numerous times. I have good reasons to believe it is due to the incorrect use of it. Anyway, it is good that you can overcome the hurdle and continue the work. Look forward to see your first example.

**Comment by LandonTClipp** [comment]
It is most certainly something I'm doing wrong. I didn't get a chance to
figure out what I was doing wrong but it's probably something simple.

**Comment by LandonTClipp** [comment]
@kyang2014 

The reason why the program was not working was because SDdiminfo was returning 0 for the number type for this reason (from the HDF4 reference manual):

"If no scale information has been stored for this dimension, the value returned in the ntype parameter will be 0."

I am getting no number types returned. I am doing this for the dimension "Band_1KM_RefSB:MODIS_SWATH_Type_L1B".

How do I handle a case like this? Do I simply create a "pure dimension" in HDF5 as well with no scale information?

Edit: I understand what I can do for this now. I have successfully been able to create a pure dimension, however I am having issues attaching the dimension to the dataset. Although H5DS_attach_scale() is not giving me any errors, the 1KM dataset does not reflect having pure dimensions attached to it. The dimension names are not appearing in the "Dimension Size(s)" property field. This is confusing to me, I would think that if H5DS_attach_scale() does not throw any errors that the dimension would be properly attached with its name showing in the dataset's properties.

Also, I am curious if I must use H5Dcreate_anon (versus just H5Dcreate) to prevent the dimensions from showing up in the object tree.

I will upload the code that I have now. I will not be able to create a full example for MODIS by the deadline. Please refer to the code I have underneath the comment "CODE FOR DIMENSION SCALES".

**Comment by LandonTClipp** [comment]
I have left the result of commit 63e19a9d0c26d6eec6759a2bd3cd1672dfd246e0 in the directory .../jq0/TerraFusion/tempFiles/firstDimScales.h5 if you want to take a look at it.

**Comment by kyang2014** [comment]
The example HDF5 file  is far away from final form although you've made some progress. The HDF5 dimension scale dataset should be a one dimension dataset with the right size retrieved from HDF4. Now I see the size is 0, which is definitely not right! Unlike HDF4, the dimension names will not appear in the "Dimension Size(s)" box. The way to check if an HDF5 dataset has a dimension scale attached to it is to see if you have a DIMENSION_LIST attribute. I can see EV_1KM_RefSB has the DIMNEISION_LIST attribute. So it is attached. 

Your "NAME" attribute value is also not right.  There are more things to do for dimension scales. But first, let's get the current one correct. 
I attached two sample files. One is the original HDF4 file. sds_puredim_test_ds.hdf and another one is the converted sds_puredim_test_ds.h5 that uses the HDF5 dimension scales. 
See the attached HDF5 files(attributes especially). Don't worry about unldim0 in the example files. 


I am getting no number types returned. I am doing this for the dimension "Band_1KM_RefSB:MODIS_SWATH_Type_L1B".

How do I handle a case like this?

**Comment by kyang2014** [comment]
I cannot upload HDF4, 5 files since github doesn't support that.  I will send you an email.

**Comment by LandonTClipp** [comment]
Thank you for that info, I will be taking a look over all of this and give you an update next time I work on it.

**Comment by LandonTClipp** [comment]
Dr. Yang, I did have another question I need answered. When I use the function SDgetdiminfo (or whatever the name is, I don't recall exactly), it returns no number type and a size of zero for the dimension attached to the dataset. Perhaps you have already answered this (I apologize if you have) but in this case, what number type do I create for the pure dimension scale in the HDF5 file? Does it matter that greatly? Is it not correct that getdiminfo is returning no number type?

**Comment by kyang2014** [comment]
For the pure dimension scale, you can always use the integer-32 bit. You should obtain the dimension size from other SDS APIs.

**Comment by LandonTClipp** [comment]
I have done more with the dimension scales. I believe everything is the way it is supposed to be now. Please check the file dimScales2.h5 under .../jq0/TerraFusion/tempFiles. I am going to begin applying this to all (?) of the datasets in MODIS, it should be fairly straight forward.

The only question I have is that the dimensions are visible in the main object tree. Is this correct? Should the dimensions be visible in hdfview?

**Comment by LandonTClipp** [comment]
Other question: Will each dataset have its own individual set of dimensions, or do some datasets share dimensions? If they share dimensions then I will need a way to inquire which dimensions are shared between what datasets.

Also, as I was writing the code to determine if a dimension is pure, I recall you said "Use netCDF attribute name to identify the pure dimension", however I found that many (if not all) of the dimensions I copied over did NOT have any name attribute. They in fact had no attributes, so the only way I could tell if it was pure or not was if it had no number type. Surely this shouldn't be the case?

**Comment by kyang2014** [comment]
Dimensions are shared, That's very reason we use them.
@LandonTClipp you mixed the HDF4 with the HDF5. For the HDF4, you can just use the current way to tell(if it had number type). But, to generate the basic fusion product, we need to do a little bit more. I will write down another note for you on how to carry out the task. 

Sent using OWA for iPad
________________________________

**Comment by kyang2014** [comment]
This looks fine for one variable. We need to do for all MODIS and some modifications are needed. I will share with you in a document.


________________________________

**Comment by LandonTClipp** [comment]
Issues:

1. SDdiminfo is returning 0 for the number type of all dimension scales. Surely this isn't correct
2. I have tried reading the dimension information (including finding the underlying number type of the dataset) using SDgetinfo, but HDF4 does not seem to like the dimension ID I am passing to it.
3. I do not understand how to view the dimension scale information in HDFView if the dimension dataset is not visible in the object tree. How do I do that?

I see you said in your email that I can (for now) hard code the values into the specific dimension scales you mentioned, however I am hesitant to do that because the function I am writing to copy the dimension scales should be able to handle general cases instead of specific ones. Down the line, hard coding all of the dimensions for all of our datasets will become extremely cumbersome, so it seems that it would be best to fix the problem I'm having with SDdiminfo. However I can go ahead and hard code if you still want me to.

The output of d8106a3e6c394709534f1154c987e0683ce1aaca is stored in ...TerraFusion/tempFiles/dimScales3.h5. This file does not have the hard coded dimension scales.

**Comment by kyang2014** [comment]
Landon,


1)      For your issue 1, as I already explained to you, when datatype inside the SDdiminfo returns number type 0, it means the pure dimension. A dimension that doesn’t have the dimension scale. If you checked the HDF4 reference manunal of SDdiminfo. It states clearly about that. What do you insist that it is not correct. It is your incorrect understanding.

From : https://support.hdfgroup.org/release4/doc/RefMan_html/RM_Section_II_SD.html#wp430440
SDattrinfo/sfgainfo - support.hdfgroup.org<https://support.hdfgroup.org/release4/doc/RefMan_html/RM_Section_II_SD.html#wp430440>
support.hdfgroup.org
The parameter obj_id can be either an SD interface identifier (sd_id), returned by SDstart, a data set identifier (sds_id), returned by SDselect, or a dimension ...




If scale information has been stored for this dimension via SDsetdimscale, the ntype parameter will contain the number type. Valid number types can be found in Table 1A, Number Type Definitions<https://support.hdfgroup.org/release4/doc/RefMan_html/RM_Section_I.html#wp432530>, in this manual. If no scale information has been stored for this dimension, the value returned in the ntype parameter will be 0.



2)      For your issue 2, for the dimension that doesn’t have dimension scale, the datatype is useless.  You should not use SDgetinfo. You should use SDgetdiminfo to get the dimension size and dimension name.

3)      For your Issue 3, I think you mean the case with the pure dimension. HDF5 dimension scale should be visible in the object tree as an HDF5 dataset. Again, I’ve explained this before. You just need to create an HDF5 dataset by using H5Dcreate??, don’t write any data and add the NAME attribute. Check dim0 in sds_puredim_test_ds.h5 I sent to you before.
For your general comments about hard-coding, it is the principle I insist that we should do our best to avoid using the hard code value if possible. Here  I ask you to do this for the following reasons that override this rule:
a)  This dimension scale information  I ask you to add it comes from the MODIS user guide. Usually there is no other choice but to provide those information by just citing where we got this information,
b)  I found there is SDS stored those information. Since you are behind the schedule, I think it is fine to just use the information as I provided. Please do it.
c) Only a few dimensions we need to fill in dimension scales. Don't need to worry that there are many. It will not be overwhelming.

Kent

(a)

**Comment by LandonTClipp** [comment]
Thanks Dr. Yang,

- My hesitation was in the fact that all the dimensions being returned were pure, I thought a few of them would not be pure so that is why I was confused. Thanks for clearing it up.

- (Number 3) That makes sense, I will go ahead and add those values to the dimension as you specified.

Thank you greatly for being patient with me as I learn all of this. I also apologize for being behind schedule, it is an unfortunate consequence that I cannot dedicate as much time as I wish I could so my progress is slowed because of that. 

Do let me know any further changes that need to be made to the MODIS dimensions once I add the scales. Once that is done I can begin work on the next thing you want.

**Comment by LandonTClipp** [comment]
MODIS should be done. If you want to look, the output file is in the same directory I've been mentioning, named MODISdimScales.h5.

I will begin work on other instruments now, hopefully the process will go much quicker. I will start on the CERES dimensions now unless you want me to begin on another one.

Edit: I was able to rapidly complete the dimension scale coding for MISR, CERES and ASTER. This iteration is under the filename "2_25_2017.h5". I have placed all dimension scales under the root object tree, is this where we want all of them or should I create a group under each instrument and place their respective dimensions in there? I also assume that we will need to make some of these dimensions real dimensions.

**Comment by LandonTClipp** [comment]
@kyang2014 

In the StructMetadata.0 file, the object list has a variable named "MaxdimList." What is this list? I am currently copying over the dimensions by hand as listed in DimList, but I am not sure if I need to worry about MaxdimList.

**Comment by kyang2014** [comment]
For this project’s purpose, we don’t need to consider MaxdimList. You can simply ignore it.

Kent

**Comment by kyang2014** [comment]
This issue can also be closed.
