### ISSUE TITLE
MISR Unpack correct name

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#37]
@kyang2014 

In your MISR unpack function, you wrote code that converts the object names ending in "RDQI" to something like "Red Radiance" instead of what our correct_name function would return, which would be "Red_Radiance_RDQI". I have commented this code out and wrote the object with the name correct_name returns. I wanted to double check that what you originally wrote wasn't something we needed to keep.

**Comment by kyang2014** [comment]
You are right. The original correct name routine only aims to make the name be a valid HDF5 object name(no “/”). The CF naming convention is more strict. So please use your correct_name routine as you apply to other objects.

Kent

**Comment by LandonTClipp** [comment]
Issue resolved

**Comment by kyang2014** [comment]
Just check the code, I gave you wrong information. RDQI should be removed since only radiance should be used.  My original code should be kept and applied with CF naming rule. I will fix it.

**Comment by kyang2014** [comment]
This is corrected.

**Comment by kyang2014** [comment]
Resolved it https://github.com/TerraFusion/basicFusion/commit/825add31565424bbbba99830709558c59772727f
