### ISSUE TITLE
generateInput.sh stops working 

### ISSUE THREAD

**Issue by kyang2014** [TerraFusion/basicFusion#43]
I can use generateInput.sh to generate inputFilelist on Jan. 10th.  After Jan. 10th, there are two more check-in and the script stops working. 

The following errors occur:

./generateInput.sh /projects/sciteam/jq0/TerraFusion/oneorbit inputFiles.txt
Fatal Error:
        No MOPITT "MOP01" files were found in generated file list.
Fatal Error:
        No CERES files were found in generated file list.
Fatal Error:
        No MODIS "MOD021KM" files found or "MOD021KM" was not the first MODIS file.
Fatal Error:
        No ASTER files were found in generated file list.
Fatal Error:
        No MISR "AA" files found or "AA" was not the first MISR file.

A couple of inputFiles.txts are generated under /projects/sciteam/jq0/TerraFusion/oneorbit/MOPITT etc. 
This needs to be fixed.

**Comment by LandonTClipp** [comment]
Dr. Yang, the script requires an absolute path for the inputFiles.txt. The bash shell handling the script changes directories multiple times and exports all necessary output data to the path given to it. Giving a relative path results in undefined behavior because the shell "physically" moves around, echoing into the text file using a path relative to its current position.

I will add this to the list of things to fix.

**Comment by kyang2014** [comment]
The usage of the generateInput.sh says the following:
./generateInput.sh
Usage:
        ./generateInput.sh [relative/absolute path to all 5 instruments] [output file]

It is not clear that the output file must be an absolute path.
I support that it is good to have  “the output file” with the absolute path.  If this is the case, the usage should give the corresponding information to direct the user to do so. However,  I prefer: if the path is not provided, “the output file” should be generated under the current directory.

Kent

**Comment by LandonTClipp** [comment]
The script now is capable of handling relative paths for the output text file as well as cases where just a file name is passed. This update will be reflected during the next merge with master.

**Comment by LandonTClipp** [comment]
Fixed
