### ISSUE TITLE
input file needs to include the orbitinformation txt files and MISR High resolution lat/lon HDF4 files

### ISSUE THREAD

**Issue by kyang2014** [TerraFusion/basicFusion#44]
The orbit information will be used to subset CERES and MOPITT fields. The MISR High resolution lat/lon files need to be fused to the final HDF5 file.

The orbit file is attached. The path for the MISR High resolution files at roger is /projects/TDataFus/oneorbit/MISR/AGP_HR

[orbittotimelist.txt](https://github.com/TerraFusion/basicFusion/files/756001/orbittotimelist.txt)

**Comment by LandonTClipp** [comment]
This is outdated, we use binary file for the orbit info, not text file.
