### ISSUE TITLE
Structure of conditional statements in MODIS.c

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#45]
In MODIS.c, there is a peculiarity I noticed about how the code is structured. For most of the datasets where we are using the various "readThenWrite" functions, we have code that looks like this:

    if ( unpack == 1 )
    {
        if ( argv[2] != NULL )
        {
            Do unpacking work...
        }
    }
    else
        Do non-unpacking work

Should the non-unpacking work be also enclosed within the "if ( argv[2] != NULL )" statement?

This argv[2] check is checking for the existence of the 500m file. Why is this check being done for the datasets under the 1KM file section of code? For example, the EV_250_Aggr1km_RefSB (if unpacking is being done) checks if the 500m file exists. If the file does not exist, then this dataset is not written. Why? What relation does this dataset have to the 500m file?

**Comment by kyang2014** [comment]
If 500m and 250m are not present, EV_250_Agg1km_RefSB doesn't contain any useful data. So we don't need to convert this field at all. So the unpack option is not only unpacking the data, it also trims out the obvious non-useful data.
