### ISSUE TITLE
MOPITT Time Conversion

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#49]
The MOPITT time information needs to be converted from TAI93 Time to UTC. TAI is the proper Earth time according to atomic clocks. UTC is the adjusted TAI time that accounts for variations in Earth's orbit and rotation, it keeps terrestrial clocks roughly in sync with solar time. 

[Leap seconds](https://en.wikipedia.org/wiki/Leap_second) are periodically applied to UTC to keep clocks synchronized with solar time. Need to be especially careful how this conversion is done because the conversion is not done with a simple formula. The leap seconds are applied at the whim of the International Earth Rotation and Reference Systems Service, so the difficulty therefore is in anticipating future leap second insertions. This implies that if future basicFusion files are generated without accounting for any additional leap seconds inserted to UTC, the MOPITT time information can become inaccurate.

# **Potential Solutions**

### **Rigid solution**

Create function that is coded with a table of all known leap seconds to perform the conversion. This function would not be capable of handling future leap second insertions without manually adding new entries into the table.

This function would need to print a warning message if the table has not been updated with the latest leap second information. Leap seconds are added, if at all, at the end of June 30th and/or December 31st.

### **Elegant solution**
[Potential Elegant Solution](http://www.lsc-group.phys.uwm.edu/~ballen/grasp-distribution/GRASP/doc/html/node311.html)

The previous link provides a method for accounting for future leap seconds.

The library that may be helpful in achieving this conversion: [GRASP](http://www.lsc-group.phys.uwm.edu/~ballen/grasp-distribution/GRASP/doc/html/node3.html)

#### **Implementation 1**

Make an array where the index represents the number of days since epoch (UTC 00:00:00 1-1-1993). Each element represents the current UTC - TAI93 difference. The array must contain enough elements such that all of the MOPITT time values are represented in the array. The elements of the array must be pre-computed to contain the correct offset. For instance:

Elements 0-181 will be 0. 
Elements 182-365 will be 1. (Incremented at end of June 30th)
Elements 366-546 will be 1. (No increment happened on Dec 31st)
Elements 547-730 will be 2. (Incremented at end of June 30th)
...

Care must be taken when calculating the array elements to account for leap years where there is an extra day in the year. The corresponding array for a given TAI93 time is found by dividing the time value by the number of seconds in a day: floor(TAI93 value / 86400). Thus, the converted UTC time would be calculated as follows:

`UTC time = TAI93 time + offsetArray[ floor(TAI93 value / 86400) ] )`

Pros:

1. Finding the offset for any arbitrary TAI93 value, given the offset array is precomputed, is a constant time operation. Incredibly useful if the array is shared between all MOPITT granules.

Cons:

1. Array has to be recalculated if newer MOPITT files are computed (or alternatively, any TAI93 value that isn't properly represented by the offset array could use the last known offset in the array, i.e. the last element. However, this would result in an inaccurate converted value)

#### **Implementation 2**

A chain of if-else statements check to see how much the TAI93 value should be offset. The value would be converted to days-since-epoch as in implementation 1 using

`floor(TAI93 value / 86400) ]`

The if else chain would check to see between which two values days-since-epoch resides. For instance:

If < 182, increment 0.
If 183 <= days-since-epoch <= 546, increment 1.
If 547 <= days-since-epoch <=730, increment 2
...

Pros:

1. Extremely trivial to add support for future dates if newer MOPITT granules are added. Simply a matter of adding one extra else-if statement
2. Less memory usage than implementation 1.

Cons:

1. Terrible running time. Lower bound on running time is n*m where n=number of days since epoch and m=number of MOPITT granules to be processed. Might not be of concern on the supercomputer though.

**Comment by LandonTClipp** [comment]
@kyang2014 

The question to this problem is if we will need to consider future leap seconds. It has been discussed that the entire mission may be reprocessed in the future, and these reprocessings will include future MOPITT files which exist after more leap seconds have been inserted (these future leap seconds would not be accounted for without adjusting the conversion function).

My thoughts: Implementation 2 of the rigid solution is probably the way to go. We will probably only stick with 1 MOPITT granule so we would not get benefits from sharing an offset array. Adding a new library to this project doesn't seem ideal. Since program will not automatically account for future leap seconds, a warning should be given if a MOPITT TAI93 value is found that's outside of the dates that are supported in the code.

**Comment by kyang2014** [comment]
Good question.  For the time being, let us not consider the future leap seconds. However, we can do the following:

1)      In the user’s guide of the product, remind people to check the leap seconds of the conversion function after 2017-06-29. We need to provide the instruction on how to do add the leap second in the conversion function.

2)      In our conversion function, generate a warning message for the year after 2017-06-29 with a message to ask the use of this program to check the leap second of the time.

**Comment by kyang2014** [comment]
Don't link with another library. But if the library can figure out the future leap seconds until say 2025 or 2030. We can incorporate those leap seconds to the code. The satellite will be very possibly die by then.

**Comment by LandonTClipp** [comment]
I agree, linking another library isn't something we want. From what I've found, it is actually impossible to predict future leap seconds so they will have to be manually inserted in. I will start a Wiki page to keep track of these things we must remember to put in the final product guide. I have already created a function to convert the times, I will implement that shortly.

**Comment by kyang2014** [comment]
Great, go ahead.

**Comment by LandonTClipp** [comment]
I modified the way the time conversion function works. Instead of using an if-else tree, I initialized an array with offset values where the array index is DaysSinceEpoch. Should result in slightly better performance.

**Comment by LandonTClipp** [comment]
MOPITT time conversion is complete. The time datasets appear to be properly incremented, I would like to test more MOPITT time datasets to assure that all time periods are converted properly.

I tested time values not covered by the offsetArray, the function properly prints a warning message indicating that the time values may be invalid. Because this error can be quite significant (especially if processing the entire mission), I think we should make this more visible, more than just a warning. As it stands, whoever uses this code in the future may overlook this warning due to the fact that thousands of jobs will be run to process the mission, overlooking an error message in the program output would be a very easy thing to do.

Should we make this a fatal error? Surely scientists do not want to use potentially invalid or inaccurate data.

**Comment by LandonTClipp** [comment]
I have decided to make this a fatal error. Will document on the Wiki.
