### ISSUE TITLE
generateInput.sh needs to consider new MISR HR Lat/lon files

### ISSUE THREAD

**Issue by kyang2014** [TerraFusion/basicFusion#50]
MISR high resolution lat/lon files need to be added as the input file.
So the input filelist should add a MISR file MISR_HRLL???.hdf
For example,  /projects/TDataFus/oneorbit/MISR/AGP_HR/MISR_HRLL_P022.hdf
should be added after /projects/TDataFus/oneorbit/MISR/AGP_HR/MISR_HRLL_P022.hdf
like
/projects/TDataFus/oneorbit/MISR/AGP/MISR_AM1_AGP_P022_F01_24.hdf
/projects/TDataFus/oneorbit/MISR/MISR_AM1_GP_GMP_P022_O040110_F03_0013.hdf
/projects/TDataFus/oneorbit/MISR/AGP_HR/MISR_HRLL_P022.hdf

TODO:

Don't need to edit script. Put file that has new CERES and MISR into inputFileDebug (bwLargeInput.txt, also provide a small input with the new files).

**Comment by LandonTClipp** [comment]
The C files will need to account for this as well or else the program will break with the updated input file list. Do you want me to work on the C files as well or just the script?

**Comment by kyang2014** [comment]
I’ve taken care of the C files already. You just need to take care of the input file. More contents need to be added to the input file. I will talk with you this afternoon. You can work to convert MOPITT UTC seconds to UTC date,hour,minute,second now.

Kent

**Comment by LandonTClipp** [comment]
Script now supports the extra file. I have added two BW input txt files for large and small inputs.
