### ISSUE TITLE
Integrate ASTER high reso lat/lon fields into fusion

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#51]
Yizhao will provide code, need to integrate his code into our fusion code. Generally follow MODIS integration.

**Comment by kyang2014** [comment]
Yizhao's code has compiling errors since he is using g++ rather than gcc. Wait for him to change his code before merging them.

**Comment by kyang2014** [comment]
Yizhao fixed the interpolating code. I added the HDF5 code to generate proper high-resoultion lat/lon.
