### ISSUE TITLE
MOPITT subsetting

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#53]
Convert all MOPITT UTC time values to struct GDateInfo_t, compare with the input orbit time file (will be provided as binary). This struct will be provided on master.
-- Find the first value that is closest to the starting time (comes immediately after start time of the orbit, previous is before)
-- Find the starting point of next orbit via some sort of optimization, find value that is just before next starting point (orbit number) and the next time value is after the next orbit start time.
-- Once these indicies have been found, subset all of the datasets (Dr. Yang will provide code as an example. How to find orbit starting/ending time will be provided.)
-- Write function to find start/end index for MOPITT, then write into struct. Pass struct into MOPITT subset function.

TODO

- [X] Find information about how the binary file will be passed to MOPITT function. ~~Is this something @davidraila will provide?~~ DONE: Passed into program, name is hard coded as "orbit_info.bin".
- [x] Perform subsetting
- [x] Manually verify that MOPITT is appropriately subsetting based on interpreted TAI93 time (interpreted from the orbit start and end time).
- [x] Fix the extra dimensions being added to the datasets
- [x] Have someone double check (manually) that MOPITT is subsetting correctly.

**Comment by LandonTClipp** [comment]
MOPITT subsetting is almost done, but I am encountering significant problems converting the orbit date information to TAI93. The converted TAI93 times are larger than what is given by the MOPITT file by about 90 days.  I have checked multiple times that the MOPITT granule I'm using should reside within the orbit as defined by the orbit date information. If valid orbit TAI93 times are found, the data is all subsetted correctly (except for some extra dimensions being added to the datasets, I need to fix that).

Also, the struct being passed to my subsetting function has orbit start and end times that do not exactly match with what is listed in the orbittotimelist.txt file. The times are _about_ right, but they are a little off. 

TODO:
- [X] Try converting the MOPITT TAI93 times by hand to some sort of date, maybe days-since-epoch, and see if it matches up with orbit information.
   `The two times match up. The MOPITT granule overlaps with the orbit times.`

**Comment by LandonTClipp** [comment]
I seem to have fixed the problem. Next step is to verify that all subsetting is correct.

**Comment by LandonTClipp** [comment]
Extra dimensions fixed.

@kyang2014 , MOPITT subsetting is complete except for verification that I'll need to discuss with you about (not sure how to go about it). If you like, example file with MOPITT subsetting is given by the MOPITTsubset1.h5 file in the tempFiles directory on BW. Note that CERES isn't present in the file, I am using your CERES code.

Also just want to double check with you, I am hesitant to begin work on the CERES.c code as we discussed because I am not entirely sure where you left off with the code. I'd need to reenable the CERES data transfer in order to verify the code I will write. That may get very messy if we're both working on the same code. Let me know your thoughts.

**Comment by kyang2014** [comment]
Our work for CERES.c should be orthogonal. You don’t need to worry about subsetting part. The first step is that you only need to re-write the whole data transferring part based on my suggestions.

**Comment by kyang2014** [comment]
I double checked the MOPITT subset output. It is almost right but should have the following change:
1) The MOPITT subset should fall into the orbit. That is the starting index time should be right after the orbit starting time and the ending index should be right before the orbit ending time. The current code makes the first index right before the orbit starting time and the last index right after the orbit ending time. These two points should be removed.

2) I found that 6 seconds are added to the time values. This is not right. We should still keep the original TAI93 format. Even if we want to change to UTC, we should reduce 6 seconds instead of adding. Adding 6 seconds doesn't make sense. Anyway, we should just keep the original values. 
Example: Value at  index 1 at the current subsetted time is 4.57632576904E8
This is corrsponding to index 4274 in the original file 4.57632570904E8
A 6 seconds are added to the original value. This is not right. The original value should just be kept.

**Comment by LandonTClipp** [comment]
Hi Dr. Yang. 

I was asked to convert MOPITT time to UTC.  adding 6.0 to the TAI93 time is correct for that time period if we indeed want to convert to UTC. This calculation is done based on the definition of TAI, every so often a leap second is added or subtracted to UTC and converting to UTC must account for that, hence adding 6.0.

**Comment by LandonTClipp** [comment]
I am referring to issue #49 where I completed MOPITT time conversion.

**Comment by LandonTClipp** [comment]
I realized I may have made an error. Need to double check if TAI93 = UTC at epoch or if it equals 0. This makes a huge difference in calculations.

**Comment by kyang2014** [comment]
Using UTC is fine. Are you sure we should  add 6 seconds? If we want to convert TAI to UTC, we should subtract 6 seconds rather than adding 6 seconds between 1993 and 2007.
http://maia.usno.navy.mil/ser7/tai-utc.dat

**Comment by LandonTClipp** [comment]
I was mistaken, you are in fact correct, it should be subtracting 6.0 not adding. This is an easy change that can be made to my conversion function. However it should not be subtracting 6.0 for the entirety of 1993 to 2007 as there are multiple leap seconds added in between those two years.

**Comment by kyang2014** [comment]
Agree. Your code handles the number of leap seconds correctly. Just for 2007, the time difference is 6 seconds.

**Comment by LandonTClipp** [comment]
@kyang2014 

I actually do not like the fact that we are converting to UTC... in our final documentation we need to make it very clear that the UTC epoch for MOPITT is 1993 (because the UTC time is converted from TAI93, so it will still equal 0 at Jan 1 1993). This is anti-pattern I think, common UTC time on Linux is defined with an epoch of 1970 so this might be confusing for end users of our product. We may still need to discuss further what time format instruments use.
