### ISSUE TITLE
MOPITT dimension name and size need to be corrected for two MOPITT files

### ISSUE THREAD

**Issue by kyang2014** [TerraFusion/basicFusion#59]
MOPITT dimension size will be wrong and the dimension name will be duplicate for the case when two MOPITT files are needed for the basic fusion.
Solution: 
1) Create  HDF5 groups granule1 and possibly granule2 when the second MOPITT file is needed.
2) Make the time dimension name be the ntrack_1 or ntrack_2 if two granules are needed.
3) Provide the correct subset size to ntrack_1 and possibly ntrack_2.

**Comment by LandonTClipp** [comment]
1. granule1 is added, and granule2 is added if needed.
2. ntrack_1 and ntrack_2 are properly added as needed
3. ntrack dimensions have correct size.

This issue is resolved.
