### ISSUE TITLE
MOPITT handling valgrind test

### ISSUE THREAD

**Issue by kyang2014** [TerraFusion/basicFusion#60]
This may not be an issue, but it is good to check if the code is handling things correctly.  From valgrind on the MOPITT handling code. 

 Invalid write of size 8
==77094==    at 0x40EB5C: initializeTimeOffset (libTERRA.c:4067)
==77094==    by 0x40EBF6: TAItoUTCconvert (libTERRA.c:4109)
==77094==    by 0x40662C: MOPITTinsertDataset (libTERRA.c:457)
==77094==    by 0x411A16: MOPITT (MOPITT.c:399)
==77094==    by 0x403B20: main (main.c:215)
==77094==  Address 0x64fc060 is 0 bytes after a block of size 71,568 alloc'd
==77094==    at 0x4A0728A: malloc (vg_replace_malloc.c:299)
==77094==    by 0x40E8AF: initializeTimeOffset (libTERRA.c:4038)
==77094==    by 0x40EBF6: TAItoUTCconvert (libTERRA.c:4109)
==77094==    by 0x40662C: MOPITTinsertDataset (libTERRA.c:457)
==77094==    by 0x411A16: MOPITT (MOPITT.c:399)
==77094==    by 0x403B20: main (main.c:215)

**Comment by LandonTClipp** [comment]
This issue was fixed in a recent update to my branch.
