### ISSUE TITLE
Consider forcing program to run on compute nodes

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#62]
@kyang2014 

Since you have made the default behavior of the program to unpack the data, I recommend we force the program to run on compute nodes. Even generating basicFusion file with a small number of granules when unpacking is enabled is quite CPU intensive, it seems to me to be the courteous thing to do to no longer run our program on login nodes. I do not want to be a bad user of Blue Waters.

Forcing it to run on compute nodes would just be a matter of uncommenting the initial code block I have in main.c that performs such behavior. Obvious drawback of this is that running computations will take much longer due to queue wait time. However, part of the frequent instability you experience on BW comes from users running intensive programs on the login nodes (as I've confirmed with BW staff over this issue before). I just don't want to contribute to that. 

Let me know your thoughts.

**Comment by LandonTClipp** [comment]
Also I should mention, I've made some improvements to the jobSubmit script that makes running basicFusion with your own custom inputFiles.txt easy (instead of generating a new one each time, as it did before).

**Comment by kyang2014** [comment]
I agree that we shouldn't run the intensive job at BW's login mode. So please use the comput code. 
In fact, I discourage you to use BW for your development work. You should use roger for the testing/debugging and development. We should only use BW for the verification, and the final test.
Even for running BW at compute nodes, you can use interactive node to avoid the long queue time.

**Comment by kyang2014** [comment]
Just out of curiosity,  since we use qsub to submit a job, I had thought that we always use the compute mode this way. Are you sure we are using the login mode to run the job?

**Comment by LandonTClipp** [comment]
I think I talked to you previously about which node to run our development code on, you suggested to me that it would be fine to run the program on the login nodes (not using qsub, just execute directly) and I agreed with that, the code only took a minute to execute. Now I will use qsub to use compute nodes. Also when on interactive mode,[ you still need to use "aprun"](https://bluewaters.ncsa.illinois.edu/interactive-jobs) to execute jobs since interactive mode places you on the shared, non-compute MOM node.

**Comment by LandonTClipp** [comment]
Also, I can go ahead and uncomment my compute-node-enforcing code when I get the chance. I'll repoen this until that is complete.

**Comment by kyang2014** [comment]
Oh, I forgot or we might have mis-communcation.
