### ISSUE TITLE
CERES infinite loop

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#63]
@kyang2014 

I have detected an infinite loop somewhere in the CERES code. Program was automatically terminated by BW because it exceeded wallclock time.

Looking at main.c, CERES portion of code never calls getNextLine. That would be why infinite loop occurred.

Dr. Yang, I can handle this on Saturday. I see you have been pushing changes directly to the master branch, I recommend you push to your own develop_2 so we don't end up creating conflicts. Also I have tried to make it a rule that only currently working code makes it onto master. MOPITT multiple granule handling is almost done but I wasn't able to verify because of infinite loop problem.

**Comment by LandonTClipp** [comment]
This has been resolved.

**Comment by LandonTClipp** [comment]
Re-insert Dr. Yang's CERES handing in main.c

**Comment by kyang2014** [comment]
Somehow the merging the of code by @LandonTClipp causes the handling of CERES data missed the key line and caused the infinite loop. The current handling by @LandonTClipp may not be correct. So @kyang2014 will update the main.c. The MOPITT part will not be touched.
