### ISSUE TITLE
CERES latitude and longitude handling

### ISSUE THREAD

**Issue by kyang2014** [TerraFusion/basicFusion#66]
CERES latitude and longitude don't conform to CF conventions. The "units" is not right(degrees rather than degrees_east etc.) More than that, the latitude is co-latitude, which is actually following latitude = 90-co-latitude. longitude is within 0-360 range. This should be mapped to -180 to 180 to conform to what's inside the other instruments.

 Need to bring this to the science team for the direction on how to handle this.

**Comment by LandonTClipp** [comment]
@shashankbansal6 

You can research this.

**Comment by kyang2014** [comment]
Guangyu says this should be done in the basic fusion. Contact Guangyu for more information or having questions. Also assign Landon on this since Landon should update the basic fusion code to include this after knowing how to do this.

**Comment by kyang2014** [comment]
Essentially the final latitude/longitude values  should be changed according to the certain formula (need to confirm) , the units attribute should be updated like other instruments.

**Comment by LandonTClipp** [comment]
Okay, I will have Shashank research how to do it, contact Dr. Zhao. I will then implement it in the code.

**Comment by kyang2014** [comment]
Good plan.

**Comment by LandonTClipp** [comment]
Closing this. A new issue for this can be found at #218.
