### ISSUE TITLE
"coordinates" attribute needs to be added. 

### ISSUE THREAD

**Issue by kyang2014** [TerraFusion/basicFusion#67]
For all the physical(radiance) variables
For example: for this variable,  ImageData4 under /ASTER/gruanule11/SWIR
We should add coordinates attributes with its latitude and longitude. In this case,
coordinates="/ASTER/granule11/SWIR/Geolocation/Latitude /ASTER/granule11/SWIR/Geolocation/Longitude"

This only applies to MISR, MODIS and ASTER.

**Comment by kyang2014** [comment]
Get a full path of an HDF5 dataset
https://support.hdfgroup.org/HDF5/doc/RM/RM_H5I.html#Identify-GetName

**Comment by LandonTClipp** [comment]
7893001 commit message is incorrect. It is for MODIS, not MISR.

**Comment by LandonTClipp** [comment]
All medium priority issues done. Next step is to generate example files to assure there are no problems with the issues that have been fixed.

**Comment by kyang2014** [comment]
Good progress! Look forward to seeing your example file.
