### ISSUE TITLE
MOD06 files extraneously included

### ISSUE THREAD

**Issue by davidraila** [TerraFusion/basicFusion#77]
From https://github.com/TerraFusion/basicFusion/issues/73#issuecomment-297760590
Reposted on behalf of https://github.com/LandonTClipp

MOD06 files inadvertently included in file meta DB, and returned from query.

**Comment by davidraila** [comment]
I understood this to be on roger.   Will add what I believe to be the proper filter.

**Comment by LandonTClipp** [comment]
This is fixed
