### ISSUE TITLE
Add ASTER sun/view geometry variables 

### ISSUE THREAD

**Issue by kyang2014** [TerraFusion/basicFusion#82]
The ASTER's geometry variables need to be added for each granule.
The information should be retrieved from productmeta.0. 
One variable should be pointing angle. We will wait another variable's information from Guangyu.

**Comment by kyang2014** [comment]
1. ASTER SOLAR ANGLES

Unlike the other instruments, the ASTER L1T doesn’t contain the satellite azimuth and zenith angles.  

So we have to pack into the basic fusion product all the necessary angles the ASTER L1T provides as follows. 

1) Under ProductMetadata.0:   
  OBJECT = SOLARDIRECTION
     NUM_VAL =2
      VALUE = (XXXX, XXXX)
   END_OBJECT = SOLARDIRECTION
  This attribute defines the sun direction as seen from the scene center, and includes two values. The first value is the SOLAR AZIMUTH angle in degrees (values can range between 0 and 360) measured eastward from North. The second value is the SOLARELEVATION angle in degrees (values can range between <= -90 to <= 90) 

2) Under ProductMetadata.0:  
    	GROUP = POINTINGANGLES
                   OBJECT = SENSORNAME
                               CLASS = “1”
                               NUM_VAL=“1”
                               VALUE = “VNIR”
                    OBJECT = POINTINGANGLE
                               CLASS = “1”
                               NUM_VAL=“1”
                               VALUE = “X.XXX”
                    OBJECT = SENSORNAME
                               CLASS = “1”
                               NUM_VAL=“1”
                               VALUE = “SWIR”
                    OBJECT = POINTINGANGLE
                               CLASS = “1”
                               NUM_VAL=“1”
                               VALUE = “X.XXX”
                   OBJECT = SENSORNAME
                               CLASS = “1”
                               NUM_VAL=“1”
                               VALUE = “TIR”
                  OBJECT = POINTINGANGLE
                               CLASS = “1”
                               NUM_VAL=“1”
                               VALUE = “X.XXX”
     This provides the pointing angle values for each of the three sensors (VNIR, SWIR, and TIR) in floating point decimal degrees. They range from +/- 24 telescope rotation for VNIR to +/- 8.55 pointing mirror rotation and scan mirror rotation for SWIR and VNIR sensors respectively.

we can pack them as SDS arrays.

**Comment by kyang2014** [comment]
I. 
I. Search this OBJECT = SOLARDIRECTION from  ProductMetadata.0
OBJECT = SOLARDIRECTION
NUM_VAL =2
VALUE = (XXXX, XXXX)
END_OBJECT = SOLARDIRECTION

Save the values to two HDF5 datasets SolarAzimuth and SolarElevation 1 element arrays under a new group Solar_Geometry. 
II. Under ProductMetadata.0,   Search Group = POINTINGANGLES and END_Group POINTINGANGLES 
Generate a substring  that contains the contents between these two lines.
Search OBJECT = SENSORNAME then search VALUE, make VALUE to be the HDF5 dataset name in the BF h5 file.
Seacrh OBJECT = POINTINGANGLE then search VALUE, make VALUE to be the value of the HDF5 dataset name
The output should either two or three HDF5 datasets with 1 element  floating-point data for each dataset. 

The HDF5 dataset names should be either TIR or SWIR or VIR.  If not, generating an error.

These datasets should be under a new group PointingAngle under the group granuleXXX.

**Comment by LandonTClipp** [comment]
Just to clarify so the code I write will not break, ASTER should always have SWIR and TIR but may not have VIR, correct?

**Comment by kyang2014** [comment]
Although I think so, we had better not assume that. Or you can check the ASTER user’s guide to verify.

**Comment by kyang2014** [comment]
VNIR(not VIR) is the one that doesn’t always exist based on our one orbit testing. We assume this is the case in our code already.
But still check the user’s guide ( AST_L1T Product User’s guide) first. If still not clear,ping guangyu.

From: Kent Yang
Sent: Tuesday, May 23, 2017 2:20 PM
To: 'TerraFusion/basicFusion'; TerraFusion/basicFusion
Cc: Assign
Subject: RE: [TerraFusion/basicFusion] Add ASTER sun/view geometry variables (#82)

Although I think so, we had better not assume that. Or you can check the ASTER user’s guide to verify.

**Comment by LandonTClipp** [comment]
Right, I remember we talked about that. I will not make the assumption that they should exist.

**Comment by LandonTClipp** [comment]
I think in this case, what the user's guide says does not matter because even if they are supposed to be in the file, if they are not in the file then that is not our problem. Need to keep reminding myself that this is "basic fusion" and we are only fusing what exists in the files.

Edit: I just looked at the user guide, we cannot safely assume that any of the bands exist. SWIR for instance does not exist after April 1, 2008.

**Comment by LandonTClipp** [comment]
I have implemented everything in here. I wanted to double check the allowable range for some of the values. Dr. Zhao originally said here:

"They range from +/- 24 telescope rotation for VNIR to +/- 8.55 pointing mirror rotation and scan mirror rotation for SWIR and VNIR sensors respectively."

For one of the SWIR values, I have 8.586 which is not vastly divergent from the range he provided, but I need a more accurate range if I am to do bound checking. Should I worry about bound checking at all?
