### ISSUE TITLE
update the basicfusion asterLatLonPlanar function to asterLatLonSpherical

### ISSUE THREAD

**Issue by kyang2014** [TerraFusion/basicFusion#88]
Yizhao updated the asterLatLonPlanar, now it is more efficient. Guangyu suggested we use asterLatLonSpherical  instead of asterLatLonPlanar. 
So we need update the code that uses the function name asterLatLonPlanar to asterLatLonSpherical. No need to change any parameters.

**Comment by LandonTClipp** [comment]
Done
