### ISSUE TITLE
May replace FilePath with GranuleName

### ISSUE THREAD

**Issue by kyang2014** [TerraFusion/basicFusion#99]
NOT the attribute  FileNath="/XXX/XXX/MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_AA_F03_0024.hdf"
BUT the attribute  GranuleName=" MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_AA_F03_0024.hdf"

**Comment by LandonTClipp** [comment]
Is this confirmed that you want me to do this?
